root_directory: data
listen_port: 5993
log_level: info
stop_grace_period: 0
wal_rotate_interval: 5
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      filter: nasdaq
      destinations: [ '5Min', '15Min', '1H', '1D' ]
bgworkers:
  - module: polygon.so
    name: Polygon
    config:
      api_key: your_polygon_key
      base_url: https://api.polygon.io
      nats_servers: nats://nats1.polygon.io:30401, nats://nats2.polygon.io:30402, nats://nats3.polygon.io:30403
      data_types: [ 'bars', 'quotes', 'trades' ]