// Code generated by "stringer -type=PrimaryExpressionEnum"; DO NOT EDIT

package SQLParser

import "fmt"

const _PrimaryExpressionEnum_name = "NULL_LITERALPARAMETERSTRING_LITERALBINARY_LITERALDECIMAL_LITERALINTEGER_LITERALBOOLEAN_LITERALTYPE_CONSTRUCTORINTERVAL_LITERALPOSITIONROW_CONSTRUCTORFUNCTION_CALLLAMBDASUBQUERY_EXPRESSIONEXISTSSIMPLE_CASESEARCHED_CASECASTARRAY_CONSTRUCTORSUBSCRIPTCOLUMN_REFERENCEDEREFERENCESPECIAL_DATE_TIME_FUNCTIONSUBSTRINGNORMALIZEEXTRACTPARENTHESIZED_EXPRESSION"

var _PrimaryExpressionEnum_index = [...]uint16{0, 12, 21, 35, 49, 64, 79, 94, 110, 126, 134, 149, 162, 168, 187, 193, 204, 217, 221, 238, 247, 263, 274, 300, 309, 318, 325, 349}

func (i PrimaryExpressionEnum) String() string {
	i -= 1
	if i >= PrimaryExpressionEnum(len(_PrimaryExpressionEnum_index)-1) {
		return fmt.Sprintf("PrimaryExpressionEnum(%d)", i+1)
	}
	return _PrimaryExpressionEnum_name[_PrimaryExpressionEnum_index[i]:_PrimaryExpressionEnum_index[i+1]]
}
