#FROM alpacamarkets/marketstore:v2.3.8
FROM alpacamarkets/marketstore:v3.0.1

# adding bash util
RUN apk add --update bash && apk add --update tar && rm -rf /var/cache/apk/*
#RUN mkdir -p /project/data/mktsdb
