// Code generated by "stringer -type=EnumElementType,EnumRecordType datatypes.go byteconversions.go"; DO NOT EDIT.

package io

import "strconv"

const _EnumElementType_name = "FLOAT32INT32FLOAT64INT64EPOCHBYTEBOOLNONESTRINGINT16UINT8UINT16UINT32UINT64"

var _EnumElementType_index = [...]uint8{0, 7, 12, 19, 24, 29, 33, 37, 41, 47, 52, 57, 63, 69, 75}

func (i EnumElementType) String() string {
	if i >= EnumElementType(len(_EnumElementType_index)-1) {
		return "EnumElementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnumElementType_name[_EnumElementType_index[i]:_EnumElementType_index[i+1]]
}

const _EnumRecordType_name = "FIXEDVARIABLENOTYPE"

var _EnumRecordType_index = [...]uint8{0, 5, 13, 19}

func (i EnumRecordType) String() string {
	if i < 0 || i >= EnumRecordType(len(_EnumRecordType_index)-1) {
		return "EnumRecordType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnumRecordType_name[_EnumRecordType_index[i]:_EnumRecordType_index[i+1]]
}
