root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 10
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "UTC"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/1Min/Price"
    config:
      destinations:
        - 6Min
        - 12Min
        - 15Min
        - 1H
        - 1D
        - 3D
bgworkers:
  - module: quanatee_forex_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      symbols:
        - USDCAD
        - USDMXN
        - USDBRL
        - EURUSD
        - GBPUSD
        - USDCHF
        - USDDKK
        - USDNOK
        - USDSEK
        - USDRUB
        - USDTRY
        - USDAED
        - USDCNH
        - USDINR
        - KRWUSD
        - USDJPY
        - TWDUSD
        - USDHKD
        - THBUSD
        - VNDUSD
        - PHPUSD
        - USDSGD
        - AUDUSD
        - NZDUSD
        - XAGUSD
        - XAUUSD
      query_start: "2017-01-01 00:00"
      base_timeframe: "1Min"