root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 10
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "UTC"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/1Min/Price"
    config:
      destinations:
        - 5Min
        - 6Min
        - 12Min
        - 15Min
        - 30Min
        - 1H
        - 2H
        - 4H
        - 1D
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      symbols:
        - BTCUSD
        - BNBUSD
        - ETHUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      query_start: "2020-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      symbols:
        - EURUSD
        - GBPUSD
        - USDJPY 
        - AUDUSD
        - USDCAD
        - USDCHF
        - USDMXN 
        - USDBRL
        - USDDKK 
        - USDNOK 
        - USDSEK
        - USDCNH 
        - USDHKD
        - USDRUB
        - KRWUSD
        - TWDUSD
        - USDSGD
        - USDINR 
        - THBUSD
        - VNDUSD
        - PHPUSD
        - AUDUSD
        - NZDUSD
        - XAGUSD
        - XAUUSD
      query_start: "2020-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_etf_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      symbols:
        - VXX 
        - VIXY 
        - VXZ 
        - VIXM
        - USO 
        - UNG 
        - DBO 
        - BNO 
        - UGA
        - IAU 
        - SGOL
        - SLV 
        - SIVR
        - EWC 
        - FLCA 
        - EWW 
        - FLMX
        - EWZ 
        - FLBR
        - EZU 
        - VGK
        - EWU
        - EWL 
        - FLSW 
        - EDEN 
        - EWD
        - ENOR
        - MCHI 
        - FXI 
        - EWH 
        - FLHK 
        - ERUS 
        - FLRU
        - EWJ 
        - FLJP 
        - EWY 
        - FLKR 
        - EWT 
        - FLTW
        - EWA 
        - FLAU 
        - ENZL 
        - EWS 
        - INDA 
        - FLIN
        - NORW
        - DIA 
        - SPY 
        - QQQ
        - XLY 
        - XLF 
        - XLI 
        - XLK 
        - XLRE 
        - XLE 
        - XLC 
        - XLU 
        - XLV 
        - XLP 
        - XLB
        - VCSH 
        - VCIT
        - VCLT
        - SHY 
        - VGSH 
        - SCHO 
        - IEF 
        - VGIT 
        - SCHR
        - VGLT
        # TOP 100 ETFs by Trading Volume and Market Cap
        - EEM
        - GDX
        - UWT
        - XOP
        - SQQQ
        - EFA
        - HYG
        - TQQQ
        - IWM
        - UVXY
        - IEMG
        # - UWTI # Not available on polygon
        - GDXJ
        - VWO
        - VEA
        - SPXS
        - DUST
        - DWT
        - NUGT
        - TLT
        - LQD
        - IEFA
        - SPXU
        - GUSH
        - SH
        - SDS
        - OIH
        - TVIX
        - SPXL
        - JNUG
        - BKLN
        - RSX
        - IYR
        - JNK
        - ASHR
        - JDST
        - GOVT
        - UCO
        - KRE
        - OILU
        - GASL
        - AGG
        - IVV
        - VNQ
        - PFF
        - QID
        - UPRO
        - XBI
        - SCHF
        - PSQ
        - VTI
        - VOO
        - BND
        - ERX
        - USMV
        - SOXS
        - IJR
        - SPLV
        - XRT
        - VEU
        - SMH
        - BRZU
        - PGX
        - SJNK
        - EMB
        - VTV
        - IWF
        - VUG
        - VIG
        - IJH
        - IWD
        - BNDX
        - BSV
        - MBB
        - VYM
        - VO
        - VGT
        - TIP
        - ITOT
        - IVW
        - VB
        - IWB
        - SCHX
        - VXUS
        - MUB
        - IWR
        - IXUS
        - SDY
        - QUAL
        - MINT
        - IGSB
        - VV
        - BIV
        - DVY
        - IVE
        - SCHB
        - VMBS
        - IEI
        - MDY
        - VT
        - JPST
        - RSP
        - EFAV
        - XLY
        - SCHD
        - VBR
        - SCHP
        - FLOT
        - ACWI
        - IWP
        - IGIB
        - DGRO
        - VHT
        - SCHZ
        - MTUM
        - FVD
        - IWS
        - SCHG
        - VTIP
        - IAGG
        - ICSH
      query_start: "2020-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_stock_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      # DJI AND NASDAQ 100
      symbols:
        - WTI
        - ICE
        - NG
        - AAPL
        - UNH
        - HD
        - V
        - MCD
        - GS
        - MSFT
        - MMM
        - JNJ
        - WMT
        - PG
        - CAT
        - IBM
        - BA
        - DIS
        - TRV
        - JPM
        - UTX
        - AXP
        - MRK
        - NKE
        - CVX
        - VZ
        - WBA
        - INTC
        - KO
        - CSCO
        - XOM
        - PFE
        - DOW
        - AMZN
        - GOOG
        - GOOGL
        - FB
        - CMCSA
        - NFLX
        - PEP
        - ADBE
        - COST
        - NVDA
        - AMGN
        - PYPL
        - GILD
        - TXN
        - CHTR
        - TSLA
        - AVGO
        - QCOM
        - SBUX
        - TMUS
        - MDLZ
        - FISV
        - VRTX
        - INTU
        - BIIB
        - BKNG
        - ADP
        - REGN
        - ISRG
        - AMD
        - ATVI
        - MU
        - CSX
        - ILMN
        - AMAT
        - JD
        - ADSK
        - ADI
        - EXC
        - MNST
        - LRCX
        - KHC
        - XEL
        - EA
        - BIDU
        - MAR
        - CTSH
        - ROST
        - MELI
        - EBAY
        - NTES
        - NXPI
        - WDAY
        - LULU
        - VRSK
        - CSGP
        - ORLY
        - WLTW
        - SIRI
        - PAYX
        - VRSN
        - CTAS
        - XLNX
        - PCAR
        - DLTR
        - KLAC
        - ANSS
        - ALXN
        - CERN
        - SGEN
        - SPLK
        - SNPS
        - FAST
        - ASML
        - IDXX
        - CTXS
        - CDNS
        - INCY
        - MCHP
        - CPRT
        - CHKP
        - BMRN
        - SWKS
        - TCOM
        - MXIM
        - ALGN
        - CDW
        - TTWO
        - WDC
        - ULTA
        - NTAP
        - FOXA
        - LBTYK
        - EXPE
        - UAL
        - FOX
        - AAL
        - LBTYA
      query_start: "2020-01-01 00:00"
      base_timeframe: "1Min"