root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/1Min/*"
    config:
      destinations:
        - 7Min
        - 13Min
        - 1H
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      indices:
        CC-US: ["BTCUSD", "ETHUSD", "ETCUSD", "EOSUSD", "LTCUSD", "XLMUSD", "XRPUSD"]
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<intrinio_api_key>"
      symbols:
        - EURUSD
        - USDJPY
        - GBPUSD
        - AUDUSD
        - USDCHF
        - NZDUSD
        - USDCAD
      indices:
        FX-US: ["USDEUR", "USDJPY", "USDGBP", "USDAUD", "USDCHF", "USDNZD", "USDCAD"]
        FX-US-EU: ["USDEUR", "USDGBP", "USDCHF"]
        FX-US-AS: ["USDJPY", "USDAUD", "USDNZD"]
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_stock_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<tdameritrade_api_key>"
      indices:
        ETF-US: ["ETF-US-EQ", "ETF-US-CB", "ETF-US-GB"]
        ETF-US-EQ: ["SPY", "IVV", "VOO", "VTI", "QQQ", "IJH", "VTV"]
        ETF-US-EC-HI: ["ETF-US-CD", "ETF-US-FI", "ETF-US-ID", "ETF-US-IT", "ETF-US-RE"]
        ETF-US-MC-HI: ["ETF-US-ID", "ETF-US-IT"]
        ETF-US-LC-HI: ["ETF-US-CS", "ETF-US-EN", "ETF-US-HC", "ETF-US-MA", "ETF-US-UT"]
        ETF-US-RC-HI: ["ETF-US-CS", "ETF-US-HC", "ETF-US-TE", "ETF-US-UT"]
        ETF-US-EC-LO: ["ETF-US-EN", "ETF-US-TE", "ETF-US-UT", "ETF-US-HC", "ETF-US-CS"]
        ETF-US-MC-LO: ["ETF-US-MA", "ETF-US-UT"]
        ETF-US-LC-LO: ["ETF-US-CD", "ETF-US-IT"]
        ETF-US-RC-LO: ["ETF-US-ID", "ETF-US-IT", "ETF-US-FI", "ETF-US-MA", "ETF-US-RE"]
        ETF-US-CD: ["XLY", "VCR", "IYC"]
        ETF-US-CS: ["XLP", "VDC", "IYK"]
        ETF-US-EN: ["XLE", "VDE", "IYE"]
        ETF-US-FI: ["XLF", "VFH", "IYF"]
        ETF-US-HC: ["XLV", "VHT", "IYH"]
        ETF-US-ID: ["XLI", "VIS", "IYJ"]
        ETF-US-IT: ["XLK", "VGT", "IYW"]
        ETF-US-MA: ["XLB", "VAW", "IYM"]
        ETF-US-RE: ["XLRE", "VNQ", "IYR"]
        ETF-US-TE: ["XTL", "VOX", "IYZ"]
        ETF-US-UT: ["XLU", "VPU", "IDU"]
        ETF-US-CB: ["ETF-US-CB-ST", "ETF-US-CB-MT", "ETF-US-CB-LT"]
        ETF-US-CB-ST: ["VCSH", "SPSB"]
        ETF-US-CB-MT: ["VCIT", "HYG", "JNK", "IGIB"]
        ETF-US-CB-LT: ["VCLT", "IGLB", "SPLB"]
        ETF-US-GB: ["ETF-US-GB-ST", "ETF-US-GB-MT", "ETF-US-GB-LT"]
        ETF-US-GB-ST: ["SHY", "SCHO", "VGSH", "SPTS"]
        ETF-US-GB-MT: ["IEF", "IEI", "SCHR", "VGIT"]
        ETF-US-GB-LT: ["TLT", "SPTL", "VGLT"]
        ETF-CM: ["DBA", "JJA", "RJA", "UAG", "DBE", "JJE", "VDE", "XLE", "ICLN", "GLD", "IAU", "SGOL", "DBB", "JJM", "RJZ", "DBP", "JJP", "GLTR"]
        ETF-CM-AG: ["DBA", "JJA", "RJA", "UAG"]
        ETF-CM-EN: ["DBE", "JJE", "VDE", "XLE", "ICLN"]
        ETF-CM-GD: ["GLD", "IAU", "SGOL"]
        ETF-CM-IM: ["DBB", "JJM", "RJZ"]
        ETF-CM-PM: ["DBP", "JJP", "GLTR"]
        ETF-DM: ["VEA", "EFA", "VEU", "SCHF", "IXUS", "VXUS", "IHY", "HYXU", "PICB", "BWX", "IGOV", "BWZ", "ISHG", "VNQI", "RWX", "IFGL", "WPS"]
        ETF-DM-EQ: ["VEA", "EFA", "VEU", "SCHF", "IXUS", "VXUS"]
        ETF-DM-CB: ["IHY", "HYXU", "PICB"]
        ETF-DM-GB: ["BWX", "IGOV", "BWZ", "ISHG"]
        ETF-DM-RE: ["VNQI", "RWX", "IFGL", "WPS"]
        ETF-EM: ["VWO", "IEMG", "EEM", "SCHE", "SPEM", "HYEM", "EMCB", "EMLC", "PCY", "VWOB", "EBND", "LEMB", "ELD"]
        ETF-EM-EQ: ["VWO", "IEMG", "EEM", "SCHE", "SPEM"]
        ETF-EM-CB: ["HYEM", "EMCB"]
        ETF-EM-GB: ["EMLC", "PCY", "VWOB", "EBND", "LEMB", "ELD"]
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"