root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/*"
    config:
      filter: "nasdaq"
      destinations:
        - 7Min
        - 11Min
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: tiingo_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ETHBTC
      query_start: "2019-05-01 00:00"
      base_timeframe: "1Min"
  - module: tiingo_iex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - SPY
      query_start: "2019-05-01 00:00"
      base_timeframe: "1Min"