root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/1Min/*"
    config:
      destinations:
        - 7Min
        - 11Min
        - 1H
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      indices:
        USDCC: ["BTCUSD", "ETHUSD", "ETCUSD", "EOSUSD", "LTCUSD", "XLMUSD", "XRPUSD"]
      query_start: "2018-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<intrinio_api_key>"
      symbols:
        - EURUSD
        - GBPUSD
        - AUDUSD
        - USDCHF
        - NZDUSD
        - USDCAD
        - EURGBP
        - EURAUD
        - EURCHF
        - EURNZD
        - EURCAD
        - EURJPY
        - USDJPY
        - GBPJPY
        - AUDJPY
        - CHFJPY
        - NZDJPY
        - CADJPY
      indices:
        USDFX: ["USDEUR", "USDJPY", "USDGBP", "USDAUD", "USDCHF", "USDNZD", "USDCAD"]
        EURFX: ["EURUSD", "EURJPY", "EURGBP", "EURAUD", "EURCHF", "EURNZD", "EURCAD"]
        JPYFX: ["JPYUSD", "JPYEUR", "JPYGBP", "JPYAUD", "JPYCHF", "JPYNZD", "JPYCAD"]
      query_start: "2018-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_iex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - SPY
        - IVV
        - VOO
        - VTI
        - QQQ
        - IJH
        - VTV
        - VCSH
        - IGSB
        - SPSB
        - SHV
        - SCHO
        - VGSH
        - SPTS
        - VWO
        - IEMG
        - EEM
        - SCHE
        - SPEM
        - HEEM
        - DBEM
        - HYEM
        - CEMB
        - EMCB
        - EMLC
        - PCY
        - VWOB
        - EBND
        - LEMB
        - ELD
        - EMB
        - EMIH
        - EMBH
        - JPMB
        - VEA
        - EFA
        - VEU
        - SCHF
        - IXUS
        - VXUS
        - DBEF
        - HEFA
        - HEZU
        - IHDG
        - HDEF
        - DDWM
        - DBAW
        - IHY
        - HYXU
        - BWX
        - IGOV
        - BWZ
        - ISHG
        - FLIA
        - IGVT
      indices:
        USDETF-US: ["SPY", "IVV", "VOO", "VTI", "QQQ", "IJH", "VTV", "VCSH", "IGSB", "SPSB", "VCSH", "IGSB", "SPSB", "SHV", "SCHO", "VGSH", "SPTS"]
        USDETF-US-EQ: ["SPY", "IVV", "VOO", "VTI", "QQQ", "IJH", "VTV"]
        USDETF-US-CB: ["VCSH", "IGSB", "SPSB"]
        USDETF-US-GB: ["SHV", "SCHO", "VGSH", "SPTS"]
        USDETF-DM: ["VEA", "EFA", "VEU", "SCHF", "IXUS", "VXUS", "DBEF", "HEFA", "HEZU", "IHDG", "HDEF", "DDWM", "DBAW", "IHY", "HYXU", "PICB", "BWX", "IGOV", "BWZ", "ISHG", "FLIA", "IGVT", "WIP"]
        USDETF-DM-EQ: ["VEA", "EFA", "VEU", "SCHF", "IXUS", "VXUS"]
        USDETF-DM-EQH: ["DBEF", "HEFA", "HEZU", "IHDG", "HDEF", "DDWM", "DBAW"]
        USDETF-DM-CB: ["IHY", "HYXU", "PICB"]
        USDETF-DM-GB: ["BWX", "IGOV", "BWZ", "ISHG", "FLIA"]
        USDETF-DM-GBH: ["IGVT", "WIP"]
        USDETF-EM: ["VWO", "IEMG", "EEM", "SCHE", "SPEM", "HEEM", "DBEM", "HYEM", "CEMB", "EMCB", "EMLC", "PCY", "VWOB", "EBND", "LEMB", "ELD", "EMB", "EMIH", "EMBH", "JPMB"]
        USDETF-EM-EQ: ["VWO", "IEMG", "EEM", "SCHE", "SPEM"]
        USDETF-EM-EQH: ["HEEM", "DBEM"]
        USDETF-EM-CB: ["HYEM", "CEMB", "EMCB"]
        USDETF-EM-GB: ["EMLC", "PCY", "VWOB", "EBND", "LEMB", "ELD"]
        USDETF-EM-GBH: ["EMB", "EMIH", "EMBH", "JPMB"]
      query_start: "2019-01-01 00:00"
      base_timeframe: "1Min"