root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/1Min/*"
    config:
      destinations:
        - 7Min
        - 11Min
        - 1H
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      indices:
        USDCC: ["BTCUSD", "ETHUSD", "ETCUSD", "EOSUSD", "LTCUSD", "XLMUSD", "XRPUSD"]
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<intrinio_api_key>"
      symbols:
        - EURUSD
        - GBPUSD
        - AUDUSD
        - USDCHF
        - NZDUSD
        - USDCAD
        - EURGBP
        - EURAUD
        - EURCHF
        - EURNZD
        - EURCAD
        - EURJPY
        - USDJPY
        - GBPJPY
        - AUDJPY
        - CHFJPY
        - NZDJPY
        - CADJPY
      indices:
        USDFX: ["USDEUR", "USDJPY", "USDGBP", "USDAUD", "USDCHF", "USDNZD", "USDCAD"]
        EURFX: ["EURUSD", "EURJPY", "EURGBP", "EURAUD", "EURCHF", "EURNZD", "EURCAD"]
        JPYFX: ["JPYUSD", "JPYEUR", "JPYGBP", "JPYAUD", "JPYCHF", "JPYNZD", "JPYCAD"]
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_stock_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<tdameritrade_api_key>"
      indices:
        USDETF-US: ["USDETF-US-EQ", "USDETF-US-CB", "USDETF-US-GB"]
        USDETF-US-EQ: ["SPY", "IVV", "VOO", "VTI", "QQQ", "IJH", "VTV"]
        USDETF-US-EC-HI: ["USDETF-US-CD", "USDETF-US-FI", "USDETF-US-ID", "USDETF-US-IT", "USDETF-US-RE"]
        USDETF-US-MC-HI: ["USDETF-US-ID", "USDETF-US-IT"]
        USDETF-US-LC-HI: ["USDETF-US-CS", "USDETF-US-EN", "USDETF-US-HC", "USDETF-US-MA", "USDETF-US-UT"]
        USDETF-US-RC-HI: ["USDETF-US-CS", "USDETF-US-HC", "USDETF-US-TE", "USDETF-US-UT"]
        USDETF-US-EC-LO: ["USDETF-US-EN", "USDETF-US-TE", "USDETF-US-UT", "USDETF-US-HC", "USDETF-US-CS"]
        USDETF-US-MC-LO: ["USDETF-US-MA", "USDETF-US-UT"]
        USDETF-US-LC-LO: ["USDETF-US-CD", "USDETF-US-IT"]
        USDETF-US-RC-LO: ["USDETF-US-ID", "USDETF-US-IT", "USDETF-US-FI", "USDETF-US-MA", "USDETF-US-RE"]
        USDETF-US-CD: ["XLY", "VCR", "IYC"]
        USDETF-US-CS: ["XLP", "VDC", "IYK"]
        USDETF-US-EN: ["XLE", "VDE", "IYE"]
        USDETF-US-FI: ["XLF", "VFH", "IYF"]
        USDETF-US-HC: ["XLV", "VHT", "IYH"]
        USDETF-US-ID: ["XLI", "VIS", "IYJ"]
        USDETF-US-IT: ["XLK", "VGT", "IYW"]
        USDETF-US-MA: ["XLB", "VAW", "IYM"]
        USDETF-US-RE: ["XLRE", "VNQ", "IYR"]
        USDETF-US-TE: ["XTL", "VOX", "IYZ"]
        USDETF-US-UT: ["XLU", "VPU", "IDU"]
        USDETF-US-CB: ["USDETF-US-CB-ST", "USDETF-US-CB-MT", "USDETF-US-CB-LT"]
        USDETF-US-CB-ST: ["VCSH", "SPSB"]
        USDETF-US-CB-MT: ["VCIT", "HYG", "JNK", "IGIB"]
        USDETF-US-CB-LT: ["VCLT", "IGLB", "SPLB"]
        USDETF-US-GB: ["USDETF-US-GB-ST", "USDETF-US-GB-MT", "USDETF-US-GB-LT"]
        USDETF-US-GB-ST: ["SHY", "SCHO", "VGSH", "SPTS"]
        USDETF-US-GB-MT: ["IEF", "IEI", "SCHR", "VGIT"]
        USDETF-US-GB-LT: ["TLT", "SPTL", "VGLT"]
        USDETF-DM: ["VEA", "EFA", "VEU", "SCHF", "IXUS", "VXUS", "IHY", "HYXU", "PICB", "BWX", "IGOV", "BWZ", "ISHG", "VNQI", "RWX", "IFGL", "WPS"]
        USDETF-DM-EQ: ["VEA", "EFA", "VEU", "SCHF", "IXUS", "VXUS"]
        USDETF-DM-CB: ["IHY", "HYXU", "PICB"]
        USDETF-DM-GB: ["BWX", "IGOV", "BWZ", "ISHG"]
        USDETF-DM-RE: ["VNQI", "RWX", "IFGL", "WPS"]
        USDETF-EM: ["VWO", "IEMG", "EEM", "SCHE", "SPEM", "HYEM", "EMCB", "EMLC", "PCY", "VWOB", "EBND", "LEMB", "ELD"]
        USDETF-EM-EQ: ["VWO", "IEMG", "EEM", "SCHE", "SPEM"]
        USDETF-EM-CB: ["HYEM", "EMCB"]
        USDETF-EM-GB: ["EMLC", "PCY", "VWOB", "EBND", "LEMB", "ELD"]
        USDETF-CM: ["DBA", "JJA", "RJA", "UAG", "DBE", "JJE", "VDE", "XLE", "ICLN", "GLD", "IAU", "SGOL", "DBB", "JJM", "RJZ", "DBP", "JJP", "GLTR"]
        USDETF-CM-AG: ["DBA", "JJA", "RJA", "UAG"]
        USDETF-CM-EN: ["DBE", "JJE", "VDE", "XLE", "ICLN"]
        USDETF-CM-GD: ["GLD", "IAU", "SGOL"]
        USDETF-CM-IM: ["DBB", "JJM", "RJZ"]
        USDETF-CM-PM: ["DBP", "JJP", "GLTR"]
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"