root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "UTC"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/15Min/Price"
    config:
      destinations:
        - 10Min
        - 1H
        - 1D
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - BTCUSD
        - ETHUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      query_start: "2019-07-01 00:00"
      base_timeframe: "5Min"