root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      filter: "nasdaq"
      destinations:
        - 7Min
        - 11Min
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: polygon_rest_crypto.so
    config:
      api_key: "<polygon_api_key>"
      symbols:
        - ETH
        - ETC
        - EOS
        - LTC
        - XLM
        - XRP
        - BTC
        - ETH
        - ETC
        - EOS
        - LTC
        - XLM
        - XRP        
        - BTC
        - ETH
        - ETC
        - EOS
        - LTC
        - XLM
        - XRP
      base_currencies:
        - BTC
        - USD
        - EUR
      query_start: "2019-05-01 00:00"
      base_timeframe: "1Min"