root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 10
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "UTC"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/1Min/Price"
    config:
      destinations:
        - 6Min
        - 10Min
        - 15Min
        - 1H
        - 1D
        - 3D
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<polygon_api_key>"
      symbols:
        - BTCUSD
        - BNBUSD
        - ETHUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
        - BNBBTC
        - ETHBTC
        - EOSBTC
        - LTCBTC
        - XLMBTC
        - XRPBTC
        - BNBETH
        - EOSETH
        - LTCETH
        - XLMETH
        - XRPETH
        - BTCBNB
        - EOSBNB
        - LTCBNB
        - XLMBNB
        - XRPBNB
      query_start: "2017-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<polygon_api_key>"
      symbols:
        - USDCAD
        - USDMXN
        - USDBRL
        - EURUSD
        - GBPUSD
        - USDCHF
        - USDDKK
        - USDNOK
        - USDSEK
        - USDRUB
        - USDTRY
        - USDAED
        - USDCNH
        - USDINR
        - KRWUSD
        - USDJPY
        - TWDUSD
        - USDHKD
        - THBUSD
        - VNDUSD
        - PHPUSD
        - USDSGD
        - AUDUSD
        - NZDUSD
        - XAGUSD
        - XAUUSD
      query_start: "2017-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_stock_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: ""
      symbols:
        - SPY
        - GLD
        - SLV
        - EZU
        - EWU
        - EWA
        - ENZL
        - EWC
        - MCHI
        - INDA
        - ERUS
        - EWW
        - TUR
        - EWJ
        - EWL
        - ENOR
        - EWD
        - EWS
        - XLC
        - XLY
        - XLP
        - XLE
        - XLF
        - XLV
        - XLI
        - XLK
        - XLB
        - XLRE
        - XLU
        - VCSH
        - HYG
        - VCIT
        - SHV
        - BIL
        - SHY
      query_start: "2017-01-01 00:00"
      base_timeframe: "1Min"
