root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/*"
    config:
      filter: "nasdaq"
      destinations:
        - 7Min
        - 11Min
        - 1H
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ETHBTC
        - ETCBTC
        - EOSBTC
        - LTCBTC
        - XLMBTC
        - XRPBTC
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
        - BTCEUR
        - ETHEUR
        - ETCEUR
        - EOSEUR
        - LTCEUR
        - XLMEUR
        - XRPEUR
        - BTCJPY
        - ETHJPY
        - ETCJPY
        - EOSJPY
        - LTCJPY
        - XLMJPY
        - XRPJPY
      BTC-CC:
        - ETHBTC
        - ETCBTC
        - EOSBTC
        - LTCBTC
        - XLMBTC
        - XRPBTC
      USD-CC:
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      EUR-CC:
        - BTCEUR
        - ETHEUR
        - ETCEUR
        - EOSEUR
        - LTCEUR
        - XLMEUR
        - XRPEUR
      JPY-CC:
        - BTCJPY
        - ETHJPY
        - ETCJPY
        - EOSJPY
        - LTCJPY
        - XLMJPY
        - XRPJPY
      query_start: "2018-07-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<intrinio_api_key>"
      symbols:
        - EURUSD
        - GBPUSD
        - AUDUSD
        - USDCHF
        - NZDUSD
        - USDCAD
        - EURGBP
        - EURAUD
        - EURCHF
        - EURNZD
        - EURCAD
        - EURJPY
        - USDJPY
        - GBPJPY
        - AUDJPY
        - CHFJPY
        - NZDJPY
        - CADJPY
      USD-FX:
        - EURUSD
        - JPYUSD
        - GBPUSD
        - AUDUSD
        - CHFUSD
        - NZDUSD
        - CADUSD
      EUR-FX:
        - USDEUR
        - JPYEUR
        - GBPEUR
        - AUDEUR
        - CHFEUR
        - NZDEUR
        - CADEUR
      JPY-FX:
        - USDJPY
        - EURJPY
        - GBPJPY
        - AUDJPY
        - CHFJPY
        - NZDJPY
        - CADJPY
      query_start: "2018-07-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_iex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      US-EQ:
        - SPY
        - IVV
        - VOO
        - VTI
        - QQQ
        - IJH
        - VTV
      US-CB:
        - VCSH
        - IGSB
        - SPSB
      US-GB:
        - SHV
        - SCHO
        - VGSH
        - SPTS
      US-FX:
        - UUP	
        - USDU
      EU-EQ:
        - VGK
        - EZU
        - BBEU
        - IEUR
        - FEZ
        - IEV
        - DFE
      EU-EQH:
        - HEDJ
        - HEZU
        - DBEU
        - EUSC
      EU-FX:
        - FXE
      GB-EQ:
        - EWU
        - EWUS
        - FLGB
        - FKU
      GB-EQH:
        - HEWU
      GB-FX:
        - FXB
      JP-EQ:
        - EWJ
        - BBJP
        - DFJ
        - IVLU
        - FLJP
        - JPXN
      JP-EQH:
        - DXJ
        - DBJP
        - HEWJ
      JP-FX:
        - FXY
      CH-EQ:
        - EWL
        - FSZ
        - FLSW
      CH-EQH:
        - HEWL
      CH-FX:
        - FXF
      AU-EQ:
        - EWA
        - FLAU
        - FAUS
      AU-EQH:
        - HAUD
      AU-FX:
        - FXA
      CA-EQ:
        - BBCA
        - EWC
        - ZCAN
        - FLCA
        - FCAN
      CA-EQH:
        - HEWC
      CA-FX:
        - FXC
      CN-EQ:
        - FXI
        - MCHI
        - ASHR
        - GXC
        - CQQQ
        - PGJ
      CN-EQH:
        - ASHX
        - CNHX
      CN-FX:
        - CYB
        - FXCH
      EM-EQ:
        - VWO
        - IEMG
        - EEM
        - SCHE
        - SPEM
      EM-EQH:
        - HEEM
        - DBEM
      EM-CB:
        - HYEM
        - CEMB
        - EMCB
      EM-GB:
        - EMLC
        - PCY
        - VWOB
        - EBND
        - LEMB
        - ELD
      EM-GBH:
        - EMB
        - EMIH
        - EMBH
        - JPMB
      DM-EQ:
        - VEA
        - EFA
        - VEU
        - SCHF
        - IXUS
        - VXUS
      DM-EQH:
        - DBEF
        - HEFA
        - HEZU
        - IHDG
        - HDEF
        - DDWM
        - DBAW
      DM-CB:
        - IHY
        - HYXU
      DM-GB:
        - BWX
        - IGOV
        - BWZ
        - ISHG
        - IGVT
        - FLIA
      DM-GBH:
       - IGVT
      DM-FX:
        - DBV
      query_start: "2018-07-01 00:00"
      base_timeframe: "1Min"