root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/*"
    config:
      filter: "nasdaq"
      destinations:
        - 7Min
        - 11Min
        - 1H
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: quanatee_iex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ESGD
        - ESGE
        - ESGU
        - ESML
        - SUSA
        - IDEV
        - CEW
        - GCC
        - HEDJ
        - DXJ
        - IHDG
        - DFE
        - DFJ
      ustf_symbols:
        - ESGU
        - ESML
        - SUSA
      eutf_symbols:
        - HEDJ
        - DFE
      jptf_symbols:
        - DXJ
        - DFJ
      wwtf_symbols:
        - ESGD
        - IDEV
        - IHDG
      emtf_symbols:
        - ESGE
        - CEW
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"