root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/*"
    config:
      filter: "nasdaq"
      destinations:
        - 3Min
        - 7Min
        - 11Min
        - 1H
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ETHBTC
      query_start: "2019-08-20 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<intrinio_api_key>"
      symbols:
        - EURUSD
      query_start: "2019-08-20 00:00"
      base_timeframe: "1Min"
  - module: quanatee_iex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ESGD
      query_start: "2019-08-20 00:00"
      base_timeframe: "1Min"