root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/*"
    config:
      filter: "nasdaq"
      destinations:
        - 3Min
        - 7Min
        - 11Min
        - 1H
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ETHBTC
        - ETCBTC
        - EOSBTC
        - LTCBTC
        - XLMBTC
        - XRPBTC
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
        - BTCEUR
        - ETHEUR
        - ETCEUR
        - EOSEUR
        - LTCEUR
        - XLMEUR
        - XRPEUR
      BTCZ:
        - ETHBTC
        - ETCBTC
        - EOSBTC
        - LTCBTC
        - XLMBTC
        - XRPBTC
      USDZ:
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      EURZ:
        - BTCEUR
        - ETHEUR
        - ETCEUR
        - EOSEUR
        - LTCEUR
        - XLMEUR
        - XRPEUR
      query_start: "2018-07-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<intrinio_api_key>"
      symbols:
        - EURUSD
        - GBPUSD
        - AUDUSD
        - USDCHF
        - NZDUSD
        - USDCAD
        - EURGBP
        - EURAUD
        - EURCHF
        - EURNZD
        - EURCAD
        - EURJPY
        - USDJPY
        - GBPJPY
        - AUDJPY
        - CHFJPY
        - NZDJPY
        - CADJPY
      USDX:
        - EURUSD
        - JPYUSD
        - GBPUSD
        - AUDUSD
        - CHFUSD
        - NZDUSD
        - CADUSD
      EURX:
        - USDEUR
        - JPYEUR
        - GBPEUR
        - AUDEUR
        - CHFEUR
        - NZDEUR
        - CADEUR
      JPX:
        - USDJPY
        - EURJPY
        - GBPJPY
        - AUDJPY
        - CHFJPY
        - NZDJPY
        - CADJPY
      query_start: "2018-07-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_iex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      US_EQ:
        - SPY
        - IVV
        - VOO
        - VTI
        - QQQ
        - IJH
        - VTV
      US_CB:
        - VCSH
        - IGSB
        - SPSB
      US_GB:
        - SHV
        - SCHO
        - VGSH
        - SPTS
      US_FX:
        - UUP	
        - USDU
      EU_EQ:
        - VGK
        - EZU
        - BBEU
        - IEUR
        - FEZ
        - IEV
        - DFE
      EU_EQH:
        - HEDJ
        - HEZU
        - DBEU
        - EUSC
      EU_FX:
        - FXE
      GB_EQ:
        - EWU
        - EWUS
        - FLGB
        - FKU
      GB_EQH:
        - HEWU
      GB_FX:
        - FXB
      JP_EQ:
        - EWJ
        - BBJP
        - DFJ
        - IVLU
        - FLJP
        - JPXN
      JP_EQH:
        - DXJ
        - DBJP
        - HEWJ
      JP_FX:
        - FXY
      CH_EQ:
        - EWL
        - FSZ
        - FLSW
      CH_EQH:
        - HEWL
      CH_FX:
        - FXF
      AU_EQ:
        - EWA
        - FLAU
        - FAUS
      AU_EQH:
        - HAUD
      AU_FX:
        - FXA
      CA_EQ:
        - BBCA
        - EWC
        - ZCAN
        - FLCA
        - FCAN
      CA_EQH:
        - HEWC
      CA_FX:
        - FXC
      CN_EQ:
        - FXI
        - MCHI
        - ASHR
        - GXC
        - CQQQ
        - PGJ
      CN_EQH:
        - ASHX
        - CNHX
      CN_FX:
        - CYB
        - FXCH
      EM_EQ:
        - VWO
        - IEMG
        - EEM
        - SCHE
        - SPEM
      EM_EQH:
        - HEEM
        - DBEM
      EM_CB:
        - HYEM
        - CEMB
        - EMCB
      EM_GB:
        - EMLC
        - PCY
        - VWOB
        - EBND
        - LEMB
        - ELD
      EM_GBH:
        - EMB
        - EMIH
        - EMBH
        - JPMB
      DM_EQ:
        - VEA
        - EFA
        - VEU
        - SCHF
        - IXUS
        - VXUS
      DM_EQH:
        - DBEF
        - HEFA
        - HEZU
        - IHDG
        - HDEF
        - DDWM
        - DBAW
      DM_CB:
        - IHY
        - HYXU
      DM_GB:
        - BWX
        - IGOV
        - BWZ
        - ISHG
        - IGVT
        - FLIA
      DM_GBH:
       - IGVT
      DM_FX:
        - DBV
      query_start: "2018-07-01 00:00"
      base_timeframe: "1Min"