root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/*"
    config:
      filter: "nasdaq"
      destinations:
        - 7Min
        - 11Min
        - 1H
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ETHBTC
        - ETCBTC
        - EOSBTC
        - LTCBTC
        - XLMBTC
        - XRPBTC
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
        - BTCEUR
        - ETHEUR
        - ETCEUR
        - EOSEUR
        - LTCEUR
        - XLMEUR
        - XRPEUR
      btcz_symbols:
        - ETHBTC
        - ETCBTC
        - EOSBTC
        - LTCBTC
        - XLMBTC
        - XRPBTC
      usdz_symbols:
        - BTCUSD
        - ETHUSD
        - ETCUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      eurz_symbols:
        - BTCEUR
        - ETHEUR
        - ETCEUR
        - EOSEUR
        - LTCEUR
        - XLMEUR
        - XRPEUR
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      api_key2: "<intrinio_api_key>"
      symbols:
        - EURUSD
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_iex_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
      query_start: "2019-08-01 00:00"
      base_timeframe: "1Min"