root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 5
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/*"
    config:
      filter: "nasdaq"
      destinations:
        - 7Min
        - 11Min
        - 1H
  - module: stream.so
    on: "*/*/*"
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      api_key: "<tiingo_api_key>"
      symbols:
        - ETHBTC
        - ETCBTC
        - EOSBTC
        - LTCBTC
      indices:
        BTCXX: ['BTCETH, 'BTCETC']
        BTCYY: ['BTCEOS, 'BTCLTC']
      query_start: "2018-01-01 00:00"
      base_timeframe: "1Min"