root_directory: data
listen_port: 5993
log_level: info
queryable: true
stop_grace_period: 0
wal_rotate_interval: 10
enable_add: true
enable_remove: true
enable_last_known: false
timezone: "UTC"
triggers:
  - module: stream.so
    on: "*/*/*"
  - module: quanatee_ondiskagg.so
    on: "*/1Min/Price"
    config:
      destinations:
        - 5Min
        - 6Min
        - 12Min
        - 15Min
        - 30Min
        - 1H
        - 2H
        - 4H
        - 1D
bgworkers:
  - module: quanatee_crypto_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      symbols:
        - BTCUSD
        - BNBUSD
        - ETHUSD
        - EOSUSD
        - LTCUSD
        - XLMUSD
        - XRPUSD
      query_start: "2017-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_forex_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      symbols:
        - EURUSD
        - GBPUSD
        - USDJPY 
        - AUDUSD
        - NZDUSD
        - USDCAD
        - USDCHF
        - USDCAD
        - USDMXN 
        - USDBRL
        - EURUSD
        - GBPUSD
        - USDCHF 
        - USDDKK 
        - USDNOK 
        - USDSEK
        - USDCNH 
        - USDHKD
        - USDRUB
        - USDJPY 
        - KRWUSD
        - TWDUSD
        - USDSGD
        - USDINR 
        - THBUSD
        - VNDUSD
        - PHPUSD
        - AUDUSD
        - NZDUSD
        - XAGUSD
        - XAUUSD
      query_start: "2017-01-01 00:00"
      base_timeframe: "1Min"
  - module: quanatee_stock_prices.so
    config:
      tiingo_api_key: "<tiingo_api_key>"
      polygon_api_key: "<polygon_api_key>"
      symbols:
        - VXX 
        - VIXY 
        - VXZ 
        - VIXM
        - USO 
        - UNG 
        - DBO 
        - BNO 
        - UGA
        - IAU 
        - SGOL
        - SLV 
        - SIVR
        - EWC 
        - FLCA 
        - VCN 
        - EWW 
        - FLMX
        - EWZ 
        - FLBR
        - EZU 
        - VGK 
        - EWL 
        - FLSW 
        - EDEN 
        - EWD
        - ENOR
        - MCHI 
        - FXI 
        - EWH 
        - FLHK 
        - ERUS 
        - FLRU
        - EWJ 
        - FLJP 
        - EWY 
        - FLKR 
        - EWT 
        - FLTW
        - EWA 
        - FLAU 
        - ENZL 
        - EWS 
        - INDA 
        - FLIN
        - EWC 
        - FLCA 
        - VCN
        - EWW 
        - FLMX
        - EWZ 
        - FLBR
        - EZU 
        - VGK
        - EWL 
        - FLSW
        - EDEN
        - EWD
        - ENOR 
        - NORW
        - MCHI 
        - FXI
        - EWH 
        - FLHK
        - ERUS 
        - FLRU
        - EWJ 
        - FLJP
        - EWY 
        - FLKR
        - EWT 
        - FLTW
        - EWA 
        - FLAU
        - ENZL
        - EWS
        - INDA 
        - FLIN
        - DIA 
        - SPY 
        - QQQ
        - XLY 
        - XLF 
        - XLI 
        - XLK 
        - XLRE 
        - XLE 
        - XLC 
        - XLU 
        - XLV 
        - XLP 
        - XLB
        - VCSH 
        - VCIT
        - SHY 
        - VGSH 
        - SCHO 
        - IEF 
        - VGIT 
        - SCHR
      query_start: "2017-01-01 00:00"
      base_timeframe: "1Min"
