// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marketstore.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataType int32

const (
	//
	//NOTE: The ordering of this enum must match the File Format order
	//
	//We define our own types here instead of using the (excellent!) built-in Go type system for the primary reason
	//that we are serializing data to files and so need to have a (very!) stable on-disk representation that matches
	//the processing we do internally.
	DataType_UNKNOWN DataType = 0
	DataType_FLOAT32 DataType = 1
	DataType_INT32   DataType = 2
	DataType_FLOAT64 DataType = 3
	DataType_INT64   DataType = 4
	DataType_EPOCH   DataType = 5
	DataType_BYTE    DataType = 6
	DataType_BOOL    DataType = 7
	DataType_NONE    DataType = 8
	DataType_STRING  DataType = 9
	DataType_INT16   DataType = 10
	DataType_UINT8   DataType = 11
	DataType_UINT16  DataType = 12
	DataType_UINT32  DataType = 13
	DataType_UINT64  DataType = 14
)

var DataType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "FLOAT32",
	2:  "INT32",
	3:  "FLOAT64",
	4:  "INT64",
	5:  "EPOCH",
	6:  "BYTE",
	7:  "BOOL",
	8:  "NONE",
	9:  "STRING",
	10: "INT16",
	11: "UINT8",
	12: "UINT16",
	13: "UINT32",
	14: "UINT64",
}

var DataType_value = map[string]int32{
	"UNKNOWN": 0,
	"FLOAT32": 1,
	"INT32":   2,
	"FLOAT64": 3,
	"INT64":   4,
	"EPOCH":   5,
	"BYTE":    6,
	"BOOL":    7,
	"NONE":    8,
	"STRING":  9,
	"INT16":   10,
	"UINT8":   11,
	"UINT16":  12,
	"UINT32":  13,
	"UINT64":  14,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{0}
}

type DataShape struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 DataType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.DataType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataShape) Reset()         { *m = DataShape{} }
func (m *DataShape) String() string { return proto.CompactTextString(m) }
func (*DataShape) ProtoMessage()    {}
func (*DataShape) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{0}
}

func (m *DataShape) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataShape.Unmarshal(m, b)
}
func (m *DataShape) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataShape.Marshal(b, m, deterministic)
}
func (m *DataShape) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataShape.Merge(m, src)
}
func (m *DataShape) XXX_Size() int {
	return xxx_messageInfo_DataShape.Size(m)
}
func (m *DataShape) XXX_DiscardUnknown() {
	xxx_messageInfo_DataShape.DiscardUnknown(m)
}

var xxx_messageInfo_DataShape proto.InternalMessageInfo

func (m *DataShape) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataShape) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_UNKNOWN
}

type NumpyMultiDataset struct {
	Data                 *NumpyDataset    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	StartIndex           map[string]int32 `protobuf:"bytes,2,rep,name=start_index,json=startIndex,proto3" json:"start_index,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Lengths              map[string]int32 `protobuf:"bytes,3,rep,name=lengths,proto3" json:"lengths,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NumpyMultiDataset) Reset()         { *m = NumpyMultiDataset{} }
func (m *NumpyMultiDataset) String() string { return proto.CompactTextString(m) }
func (*NumpyMultiDataset) ProtoMessage()    {}
func (*NumpyMultiDataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{1}
}

func (m *NumpyMultiDataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumpyMultiDataset.Unmarshal(m, b)
}
func (m *NumpyMultiDataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumpyMultiDataset.Marshal(b, m, deterministic)
}
func (m *NumpyMultiDataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumpyMultiDataset.Merge(m, src)
}
func (m *NumpyMultiDataset) XXX_Size() int {
	return xxx_messageInfo_NumpyMultiDataset.Size(m)
}
func (m *NumpyMultiDataset) XXX_DiscardUnknown() {
	xxx_messageInfo_NumpyMultiDataset.DiscardUnknown(m)
}

var xxx_messageInfo_NumpyMultiDataset proto.InternalMessageInfo

func (m *NumpyMultiDataset) GetData() *NumpyDataset {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *NumpyMultiDataset) GetStartIndex() map[string]int32 {
	if m != nil {
		return m.StartIndex
	}
	return nil
}

func (m *NumpyMultiDataset) GetLengths() map[string]int32 {
	if m != nil {
		return m.Lengths
	}
	return nil
}

type NumpyDataset struct {
	// a list of type strings such as i4 and f8
	ColumnTypes []string `protobuf:"bytes,1,rep,name=column_types,json=columnTypes,proto3" json:"column_types,omitempty"`
	// a list of column names
	ColumnNames []string `protobuf:"bytes,2,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
	// two dimentional byte arrays holding the column data
	ColumnData [][]byte `protobuf:"bytes,3,rep,name=column_data,json=columnData,proto3" json:"column_data,omitempty"`
	Length     int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	// hidden
	DataShapes           []*DataShape `protobuf:"bytes,5,rep,name=data_shapes,json=dataShapes,proto3" json:"data_shapes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NumpyDataset) Reset()         { *m = NumpyDataset{} }
func (m *NumpyDataset) String() string { return proto.CompactTextString(m) }
func (*NumpyDataset) ProtoMessage()    {}
func (*NumpyDataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{2}
}

func (m *NumpyDataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumpyDataset.Unmarshal(m, b)
}
func (m *NumpyDataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumpyDataset.Marshal(b, m, deterministic)
}
func (m *NumpyDataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumpyDataset.Merge(m, src)
}
func (m *NumpyDataset) XXX_Size() int {
	return xxx_messageInfo_NumpyDataset.Size(m)
}
func (m *NumpyDataset) XXX_DiscardUnknown() {
	xxx_messageInfo_NumpyDataset.DiscardUnknown(m)
}

var xxx_messageInfo_NumpyDataset proto.InternalMessageInfo

func (m *NumpyDataset) GetColumnTypes() []string {
	if m != nil {
		return m.ColumnTypes
	}
	return nil
}

func (m *NumpyDataset) GetColumnNames() []string {
	if m != nil {
		return m.ColumnNames
	}
	return nil
}

func (m *NumpyDataset) GetColumnData() [][]byte {
	if m != nil {
		return m.ColumnData
	}
	return nil
}

func (m *NumpyDataset) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *NumpyDataset) GetDataShapes() []*DataShape {
	if m != nil {
		return m.DataShapes
	}
	return nil
}

type MultiQueryRequest struct {
	//
	//A multi-request allows for different Timeframes and record formats for each request
	Requests             []*QueryRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MultiQueryRequest) Reset()         { *m = MultiQueryRequest{} }
func (m *MultiQueryRequest) String() string { return proto.CompactTextString(m) }
func (*MultiQueryRequest) ProtoMessage()    {}
func (*MultiQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{3}
}

func (m *MultiQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiQueryRequest.Unmarshal(m, b)
}
func (m *MultiQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiQueryRequest.Marshal(b, m, deterministic)
}
func (m *MultiQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiQueryRequest.Merge(m, src)
}
func (m *MultiQueryRequest) XXX_Size() int {
	return xxx_messageInfo_MultiQueryRequest.Size(m)
}
func (m *MultiQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiQueryRequest proto.InternalMessageInfo

func (m *MultiQueryRequest) GetRequests() []*QueryRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type QueryRequest struct {
	// Note: SQL is not fully supported
	IsSqlStatement bool   `protobuf:"varint,1,opt,name=is_sql_statement,json=isSqlStatement,proto3" json:"is_sql_statement,omitempty"`
	SqlStatement   string `protobuf:"bytes,2,opt,name=sql_statement,json=sqlStatement,proto3" json:"sql_statement,omitempty"`
	// Destination is <symbol>/<timeframe>/<attributegroup>
	Destination string `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	// This is not usually set, defaults to Symbol/Timeframe/AttributeGroup
	KeyCategory string `protobuf:"bytes,4,opt,name=key_category,json=keyCategory,proto3" json:"key_category,omitempty"`
	// Lower time predicate (i.e. index >= start) in unix epoch second
	EpochStart int64 `protobuf:"varint,5,opt,name=epoch_start,json=epochStart,proto3" json:"epoch_start,omitempty"`
	// fractional part (nano second) of epoch_start
	EpochStartNanos int64 `protobuf:"varint,6,opt,name=epoch_start_nanos,json=epochStartNanos,proto3" json:"epoch_start_nanos,omitempty"`
	// Upper time predicate (i.e. index <= end) in unix epoch second
	EpochEnd int64 `protobuf:"varint,7,opt,name=epoch_end,json=epochEnd,proto3" json:"epoch_end,omitempty"`
	// fractional part (nano second) of epoch_end
	EpochEndNanos int64 `protobuf:"varint,8,opt,name=epoch_end_nanos,json=epochEndNanos,proto3" json:"epoch_end_nanos,omitempty"`
	// Number of max returned rows from lower/upper bound
	LimitRecordCount int32 `protobuf:"varint,9,opt,name=limit_record_count,json=limitRecordCount,proto3" json:"limit_record_count,omitempty"`
	// Set to true if LimitRecordCount should be from the lower
	LimitFromStart bool `protobuf:"varint,10,opt,name=limit_from_start,json=limitFromStart,proto3" json:"limit_from_start,omitempty"`
	// Array of column names to be returned
	Columns []string `protobuf:"bytes,11,rep,name=columns,proto3" json:"columns,omitempty"`
	// Support for functions is experimental and subject to change
	Functions            []string `protobuf:"bytes,12,rep,name=functions,proto3" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{4}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetIsSqlStatement() bool {
	if m != nil {
		return m.IsSqlStatement
	}
	return false
}

func (m *QueryRequest) GetSqlStatement() string {
	if m != nil {
		return m.SqlStatement
	}
	return ""
}

func (m *QueryRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *QueryRequest) GetKeyCategory() string {
	if m != nil {
		return m.KeyCategory
	}
	return ""
}

func (m *QueryRequest) GetEpochStart() int64 {
	if m != nil {
		return m.EpochStart
	}
	return 0
}

func (m *QueryRequest) GetEpochStartNanos() int64 {
	if m != nil {
		return m.EpochStartNanos
	}
	return 0
}

func (m *QueryRequest) GetEpochEnd() int64 {
	if m != nil {
		return m.EpochEnd
	}
	return 0
}

func (m *QueryRequest) GetEpochEndNanos() int64 {
	if m != nil {
		return m.EpochEndNanos
	}
	return 0
}

func (m *QueryRequest) GetLimitRecordCount() int32 {
	if m != nil {
		return m.LimitRecordCount
	}
	return 0
}

func (m *QueryRequest) GetLimitFromStart() bool {
	if m != nil {
		return m.LimitFromStart
	}
	return false
}

func (m *QueryRequest) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *QueryRequest) GetFunctions() []string {
	if m != nil {
		return m.Functions
	}
	return nil
}

type MultiQueryResponse struct {
	Responses            []*QueryResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Version              string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timezone             string           `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MultiQueryResponse) Reset()         { *m = MultiQueryResponse{} }
func (m *MultiQueryResponse) String() string { return proto.CompactTextString(m) }
func (*MultiQueryResponse) ProtoMessage()    {}
func (*MultiQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{5}
}

func (m *MultiQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiQueryResponse.Unmarshal(m, b)
}
func (m *MultiQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiQueryResponse.Marshal(b, m, deterministic)
}
func (m *MultiQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiQueryResponse.Merge(m, src)
}
func (m *MultiQueryResponse) XXX_Size() int {
	return xxx_messageInfo_MultiQueryResponse.Size(m)
}
func (m *MultiQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiQueryResponse proto.InternalMessageInfo

func (m *MultiQueryResponse) GetResponses() []*QueryResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *MultiQueryResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *MultiQueryResponse) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type QueryResponse struct {
	Result               *NumpyMultiDataset `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{6}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResult() *NumpyMultiDataset {
	if m != nil {
		return m.Result
	}
	return nil
}

type MultiWriteRequest struct {
	//
	//A multi-request allows for different Timeframes and record formats for each request
	Requests             []*WriteRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MultiWriteRequest) Reset()         { *m = MultiWriteRequest{} }
func (m *MultiWriteRequest) String() string { return proto.CompactTextString(m) }
func (*MultiWriteRequest) ProtoMessage()    {}
func (*MultiWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{7}
}

func (m *MultiWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiWriteRequest.Unmarshal(m, b)
}
func (m *MultiWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiWriteRequest.Marshal(b, m, deterministic)
}
func (m *MultiWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiWriteRequest.Merge(m, src)
}
func (m *MultiWriteRequest) XXX_Size() int {
	return xxx_messageInfo_MultiWriteRequest.Size(m)
}
func (m *MultiWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiWriteRequest proto.InternalMessageInfo

func (m *MultiWriteRequest) GetRequests() []*WriteRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type WriteRequest struct {
	Data                 *NumpyMultiDataset `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IsVariableLength     bool               `protobuf:"varint,2,opt,name=is_variable_length,json=isVariableLength,proto3" json:"is_variable_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{8}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetData() *NumpyMultiDataset {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WriteRequest) GetIsVariableLength() bool {
	if m != nil {
		return m.IsVariableLength
	}
	return false
}

type MultiServerResponse struct {
	Responses            []*ServerResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MultiServerResponse) Reset()         { *m = MultiServerResponse{} }
func (m *MultiServerResponse) String() string { return proto.CompactTextString(m) }
func (*MultiServerResponse) ProtoMessage()    {}
func (*MultiServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{9}
}

func (m *MultiServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiServerResponse.Unmarshal(m, b)
}
func (m *MultiServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiServerResponse.Marshal(b, m, deterministic)
}
func (m *MultiServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiServerResponse.Merge(m, src)
}
func (m *MultiServerResponse) XXX_Size() int {
	return xxx_messageInfo_MultiServerResponse.Size(m)
}
func (m *MultiServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiServerResponse proto.InternalMessageInfo

func (m *MultiServerResponse) GetResponses() []*ServerResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type ServerResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{10}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ServerResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type MultiKeyRequest struct {
	Requests             []*KeyRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MultiKeyRequest) Reset()         { *m = MultiKeyRequest{} }
func (m *MultiKeyRequest) String() string { return proto.CompactTextString(m) }
func (*MultiKeyRequest) ProtoMessage()    {}
func (*MultiKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{11}
}

func (m *MultiKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiKeyRequest.Unmarshal(m, b)
}
func (m *MultiKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiKeyRequest.Marshal(b, m, deterministic)
}
func (m *MultiKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiKeyRequest.Merge(m, src)
}
func (m *MultiKeyRequest) XXX_Size() int {
	return xxx_messageInfo_MultiKeyRequest.Size(m)
}
func (m *MultiKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiKeyRequest proto.InternalMessageInfo

func (m *MultiKeyRequest) GetRequests() []*KeyRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type KeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyRequest) Reset()         { *m = KeyRequest{} }
func (m *KeyRequest) String() string { return proto.CompactTextString(m) }
func (*KeyRequest) ProtoMessage()    {}
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{12}
}

func (m *KeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyRequest.Unmarshal(m, b)
}
func (m *KeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyRequest.Marshal(b, m, deterministic)
}
func (m *KeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRequest.Merge(m, src)
}
func (m *KeyRequest) XXX_Size() int {
	return xxx_messageInfo_KeyRequest.Size(m)
}
func (m *KeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRequest proto.InternalMessageInfo

func (m *KeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ListSymbolsRequest struct {
	Results              []string `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSymbolsRequest) Reset()         { *m = ListSymbolsRequest{} }
func (m *ListSymbolsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSymbolsRequest) ProtoMessage()    {}
func (*ListSymbolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{13}
}

func (m *ListSymbolsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSymbolsRequest.Unmarshal(m, b)
}
func (m *ListSymbolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSymbolsRequest.Marshal(b, m, deterministic)
}
func (m *ListSymbolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSymbolsRequest.Merge(m, src)
}
func (m *ListSymbolsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSymbolsRequest.Size(m)
}
func (m *ListSymbolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSymbolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSymbolsRequest proto.InternalMessageInfo

func (m *ListSymbolsRequest) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

type ListSymbolsResponse struct {
	Results              []string `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSymbolsResponse) Reset()         { *m = ListSymbolsResponse{} }
func (m *ListSymbolsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSymbolsResponse) ProtoMessage()    {}
func (*ListSymbolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{14}
}

func (m *ListSymbolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSymbolsResponse.Unmarshal(m, b)
}
func (m *ListSymbolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSymbolsResponse.Marshal(b, m, deterministic)
}
func (m *ListSymbolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSymbolsResponse.Merge(m, src)
}
func (m *ListSymbolsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSymbolsResponse.Size(m)
}
func (m *ListSymbolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSymbolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSymbolsResponse proto.InternalMessageInfo

func (m *ListSymbolsResponse) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

type ServerVersionRequest struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerVersionRequest) Reset()         { *m = ServerVersionRequest{} }
func (m *ServerVersionRequest) String() string { return proto.CompactTextString(m) }
func (*ServerVersionRequest) ProtoMessage()    {}
func (*ServerVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{15}
}

func (m *ServerVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerVersionRequest.Unmarshal(m, b)
}
func (m *ServerVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerVersionRequest.Marshal(b, m, deterministic)
}
func (m *ServerVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerVersionRequest.Merge(m, src)
}
func (m *ServerVersionRequest) XXX_Size() int {
	return xxx_messageInfo_ServerVersionRequest.Size(m)
}
func (m *ServerVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerVersionRequest proto.InternalMessageInfo

func (m *ServerVersionRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ServerVersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerVersionResponse) Reset()         { *m = ServerVersionResponse{} }
func (m *ServerVersionResponse) String() string { return proto.CompactTextString(m) }
func (*ServerVersionResponse) ProtoMessage()    {}
func (*ServerVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a89eb64cdc1fc4a5, []int{16}
}

func (m *ServerVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerVersionResponse.Unmarshal(m, b)
}
func (m *ServerVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerVersionResponse.Marshal(b, m, deterministic)
}
func (m *ServerVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerVersionResponse.Merge(m, src)
}
func (m *ServerVersionResponse) XXX_Size() int {
	return xxx_messageInfo_ServerVersionResponse.Size(m)
}
func (m *ServerVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerVersionResponse proto.InternalMessageInfo

func (m *ServerVersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.DataType", DataType_name, DataType_value)
	proto.RegisterType((*DataShape)(nil), "proto.DataShape")
	proto.RegisterType((*NumpyMultiDataset)(nil), "proto.NumpyMultiDataset")
	proto.RegisterMapType((map[string]int32)(nil), "proto.NumpyMultiDataset.LengthsEntry")
	proto.RegisterMapType((map[string]int32)(nil), "proto.NumpyMultiDataset.StartIndexEntry")
	proto.RegisterType((*NumpyDataset)(nil), "proto.NumpyDataset")
	proto.RegisterType((*MultiQueryRequest)(nil), "proto.MultiQueryRequest")
	proto.RegisterType((*QueryRequest)(nil), "proto.QueryRequest")
	proto.RegisterType((*MultiQueryResponse)(nil), "proto.MultiQueryResponse")
	proto.RegisterType((*QueryResponse)(nil), "proto.QueryResponse")
	proto.RegisterType((*MultiWriteRequest)(nil), "proto.MultiWriteRequest")
	proto.RegisterType((*WriteRequest)(nil), "proto.WriteRequest")
	proto.RegisterType((*MultiServerResponse)(nil), "proto.MultiServerResponse")
	proto.RegisterType((*ServerResponse)(nil), "proto.ServerResponse")
	proto.RegisterType((*MultiKeyRequest)(nil), "proto.MultiKeyRequest")
	proto.RegisterType((*KeyRequest)(nil), "proto.KeyRequest")
	proto.RegisterType((*ListSymbolsRequest)(nil), "proto.ListSymbolsRequest")
	proto.RegisterType((*ListSymbolsResponse)(nil), "proto.ListSymbolsResponse")
	proto.RegisterType((*ServerVersionRequest)(nil), "proto.ServerVersionRequest")
	proto.RegisterType((*ServerVersionResponse)(nil), "proto.ServerVersionResponse")
}

func init() {
	proto.RegisterFile("marketstore.proto", fileDescriptor_a89eb64cdc1fc4a5)
}

var fileDescriptor_a89eb64cdc1fc4a5 = []byte{
	// 1068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x5b, 0x4f, 0xdc, 0x46,
	0x14, 0xee, 0xde, 0x77, 0x8f, 0x17, 0x30, 0x13, 0x12, 0xb9, 0x4b, 0xd4, 0x6e, 0x1d, 0xb5, 0x5d,
	0x45, 0x14, 0xc2, 0x82, 0x50, 0x14, 0x15, 0x35, 0x29, 0x90, 0x96, 0x84, 0x78, 0x5b, 0x2f, 0x24,
	0xea, 0x93, 0x65, 0x76, 0x07, 0x70, 0xf1, 0x65, 0x99, 0x19, 0xa3, 0xba, 0x0f, 0xfd, 0x59, 0x7d,
	0xae, 0xd4, 0xfe, 0x8b, 0xfe, 0x99, 0x6a, 0x2e, 0xf6, 0x8e, 0xb9, 0xb4, 0xea, 0x13, 0xe7, 0xf2,
	0x9d, 0xe3, 0x39, 0xdf, 0xf9, 0x66, 0x16, 0x58, 0x8e, 0x7c, 0x72, 0x89, 0x19, 0x65, 0x09, 0xc1,
	0xeb, 0x33, 0x92, 0xb0, 0x04, 0x35, 0xc4, 0x9f, 0xde, 0xea, 0x79, 0x92, 0x9c, 0x87, 0x78, 0x43,
	0x78, 0xa7, 0xe9, 0xd9, 0x06, 0x8e, 0x66, 0x2c, 0x93, 0x18, 0x7b, 0x1f, 0x3a, 0xfb, 0x3e, 0xf3,
	0xc7, 0x17, 0xfe, 0x0c, 0x23, 0x04, 0xf5, 0xd8, 0x8f, 0xb0, 0x55, 0xe9, 0x57, 0x06, 0x1d, 0x57,
	0xd8, 0xe8, 0x09, 0xd4, 0x59, 0x36, 0xc3, 0x56, 0xb5, 0x5f, 0x19, 0x2c, 0x0e, 0x97, 0x64, 0xd9,
	0x3a, 0xaf, 0x39, 0xce, 0x66, 0xd8, 0x15, 0x49, 0xfb, 0xcf, 0x2a, 0x2c, 0x3b, 0x69, 0x34, 0xcb,
	0xde, 0xa5, 0x21, 0x0b, 0x78, 0x92, 0x62, 0x86, 0xbe, 0x84, 0xfa, 0xd4, 0x67, 0xbe, 0x68, 0x67,
	0x0c, 0x1f, 0xa8, 0x52, 0x81, 0x53, 0x10, 0x57, 0x00, 0xd0, 0x21, 0x18, 0x94, 0xf9, 0x84, 0x79,
	0x41, 0x3c, 0xc5, 0xbf, 0x58, 0xd5, 0x7e, 0x6d, 0x60, 0x0c, 0x07, 0x3a, 0x5e, 0xef, 0xbb, 0x3e,
	0xe6, 0xd8, 0x43, 0x0e, 0x3d, 0x88, 0x19, 0xc9, 0x5c, 0xa0, 0x45, 0x00, 0x7d, 0x03, 0xad, 0x10,
	0xc7, 0xe7, 0xec, 0x82, 0x5a, 0x35, 0xd1, 0xe6, 0xf3, 0x7b, 0xdb, 0x1c, 0x49, 0x9c, 0xec, 0x91,
	0x57, 0xf5, 0x76, 0x61, 0xe9, 0x46, 0x7f, 0x64, 0x42, 0xed, 0x12, 0x67, 0x8a, 0x15, 0x6e, 0xa2,
	0x15, 0x68, 0x5c, 0xfb, 0x61, 0x2a, 0x59, 0x69, 0xb8, 0xd2, 0x79, 0x51, 0x7d, 0x5e, 0xe9, 0xbd,
	0x80, 0xae, 0xde, 0xf7, 0xff, 0xd4, 0xda, 0x7f, 0x54, 0xa0, 0xab, 0xb3, 0x83, 0x3e, 0x83, 0xee,
	0x24, 0x09, 0xd3, 0x28, 0xf6, 0x38, 0xcb, 0xd4, 0xaa, 0xf4, 0x6b, 0x83, 0x8e, 0x6b, 0xc8, 0x18,
	0xa7, 0x9f, 0x6a, 0x10, 0xbe, 0x2d, 0x2a, 0xb8, 0x2b, 0x20, 0x0e, 0x0f, 0xa1, 0x4f, 0x41, 0xb9,
	0x9e, 0xd8, 0x06, 0xa7, 0xa5, 0xeb, 0x82, 0x0c, 0xf1, 0x2f, 0xa1, 0x47, 0xd0, 0x94, 0xd3, 0x5b,
	0x75, 0x71, 0x24, 0xe5, 0xa1, 0x4d, 0x30, 0x78, 0x85, 0x47, 0xb9, 0x38, 0xa8, 0xd5, 0x10, 0x7c,
	0x9a, 0x9a, 0x02, 0x84, 0x6a, 0x5c, 0x98, 0xe6, 0x26, 0xb5, 0xf7, 0x61, 0x59, 0x70, 0xfc, 0x63,
	0x8a, 0x49, 0xe6, 0xe2, 0xab, 0x14, 0x53, 0x86, 0x36, 0xa0, 0x4d, 0xa4, 0x29, 0x47, 0x98, 0x6b,
	0x41, 0x87, 0xb9, 0x05, 0xc8, 0xfe, 0xab, 0x06, 0xdd, 0x52, 0x87, 0x01, 0x98, 0x01, 0xf5, 0xe8,
	0x55, 0xe8, 0x51, 0xe6, 0x33, 0x1c, 0xe1, 0x98, 0x09, 0x4a, 0xdb, 0xee, 0x62, 0x40, 0xc7, 0x57,
	0xe1, 0x38, 0x8f, 0xa2, 0x27, 0xb0, 0x50, 0x86, 0x55, 0x05, 0xf3, 0x5d, 0xaa, 0x83, 0xfa, 0x60,
	0x4c, 0x31, 0x65, 0x41, 0xec, 0xb3, 0x20, 0x89, 0xad, 0x9a, 0x80, 0xe8, 0x21, 0x4e, 0xeb, 0x25,
	0xce, 0xbc, 0x89, 0xcf, 0xf0, 0x79, 0x42, 0x32, 0x41, 0x4c, 0xc7, 0x35, 0x2e, 0x71, 0xb6, 0xa7,
	0x42, 0x9c, 0x56, 0x3c, 0x4b, 0x26, 0x17, 0x9e, 0x50, 0x9f, 0xd5, 0xe8, 0x57, 0x06, 0x35, 0x17,
	0x44, 0x48, 0x08, 0x08, 0x3d, 0x85, 0x65, 0x0d, 0xe0, 0xc5, 0x7e, 0x9c, 0x50, 0xab, 0x29, 0x60,
	0x4b, 0x73, 0x98, 0xc3, 0xc3, 0x68, 0x15, 0x3a, 0x12, 0x8b, 0xe3, 0xa9, 0xd5, 0x12, 0x98, 0xb6,
	0x08, 0x1c, 0xc4, 0x53, 0xf4, 0x05, 0x2c, 0x15, 0x49, 0xd5, 0xa6, 0x2d, 0x20, 0x0b, 0x39, 0x44,
	0x36, 0x59, 0x03, 0x14, 0x06, 0x51, 0xc0, 0x3c, 0x82, 0x27, 0x09, 0x99, 0x7a, 0x93, 0x24, 0x8d,
	0x99, 0xd5, 0x11, 0x3b, 0x35, 0x45, 0xc6, 0x15, 0x89, 0x3d, 0x1e, 0xe7, 0x9c, 0x4a, 0xf4, 0x19,
	0x49, 0x22, 0x35, 0x04, 0x48, 0x4e, 0x45, 0xfc, 0x35, 0x49, 0x22, 0x39, 0x88, 0x05, 0x2d, 0xa9,
	0x16, 0x6a, 0x19, 0x42, 0x5e, 0xb9, 0x8b, 0x1e, 0x43, 0xe7, 0x2c, 0x8d, 0x27, 0x9c, 0x32, 0x6a,
	0x75, 0x45, 0x6e, 0x1e, 0xb0, 0x7f, 0x03, 0xa4, 0x8b, 0x81, 0xce, 0x92, 0x98, 0x62, 0x34, 0x84,
	0x0e, 0x51, 0x76, 0x2e, 0x87, 0x95, 0xb2, 0x1c, 0x64, 0xd2, 0x9d, 0xc3, 0xf8, 0x09, 0xae, 0x31,
	0xa1, 0x7c, 0x59, 0x72, 0x9f, 0xb9, 0x8b, 0x7a, 0xd0, 0x66, 0x41, 0x84, 0x7f, 0x4d, 0x62, 0xac,
	0xf6, 0x58, 0xf8, 0xf6, 0x2b, 0x58, 0x28, 0x7f, 0xfa, 0x19, 0x34, 0x09, 0xa6, 0x69, 0xc8, 0xd4,
	0x93, 0x64, 0xdd, 0xf7, 0x36, 0xb8, 0x0a, 0x57, 0xe8, 0xf9, 0x03, 0x09, 0x18, 0xfe, 0x6f, 0x3d,
	0xeb, 0x30, 0x4d, 0xcf, 0x3f, 0x43, 0xb7, 0xd4, 0x60, 0xad, 0xf4, 0x30, 0xde, 0x7f, 0x0a, 0xf9,
	0x3a, 0xae, 0x01, 0x0a, 0xa8, 0x77, 0xed, 0x93, 0xc0, 0x3f, 0x0d, 0xb1, 0xa7, 0xae, 0x6a, 0x55,
	0xac, 0xca, 0x0c, 0xe8, 0x7b, 0x95, 0x90, 0xcf, 0x8e, 0xfd, 0x06, 0x1e, 0x88, 0x1e, 0x63, 0x4c,
	0xae, 0x31, 0x29, 0x46, 0xdf, 0xba, 0xcd, 0xfa, 0x43, 0xf5, 0xdd, 0x32, 0x52, 0xa3, 0xdd, 0x7e,
	0x09, 0x8b, 0x37, 0xda, 0xac, 0x40, 0x03, 0x13, 0x92, 0x10, 0xf5, 0xa0, 0x49, 0xe7, 0xfe, 0xf5,
	0xd8, 0x2f, 0x61, 0x49, 0x9c, 0xe6, 0x2d, 0x2e, 0xee, 0xf2, 0x57, 0xb7, 0xd8, 0x5b, 0x56, 0x07,
	0x99, 0x83, 0x34, 0xee, 0x3e, 0x01, 0xd0, 0x8a, 0x6f, 0x3d, 0xa7, 0xf6, 0x3a, 0xa0, 0xa3, 0x80,
	0xb2, 0x71, 0x16, 0x9d, 0x26, 0x21, 0xcd, 0x71, 0x16, 0xb4, 0xe4, 0x06, 0xf3, 0x47, 0x33, 0x77,
	0xed, 0x0d, 0x78, 0x50, 0xc2, 0xab, 0xc1, 0xee, 0x2f, 0x78, 0x06, 0x2b, 0x92, 0x84, 0xf7, 0x72,
	0x26, 0xed, 0x13, 0xf9, 0xd0, 0x95, 0xf2, 0xd0, 0x9b, 0xf0, 0xf0, 0x46, 0xc5, 0xfc, 0x23, 0x77,
	0x97, 0x3c, 0xfd, 0xbd, 0x02, 0xed, 0xfc, 0x37, 0x15, 0x19, 0xd0, 0x3a, 0x71, 0xde, 0x3a, 0xa3,
	0x0f, 0x8e, 0xf9, 0x11, 0x77, 0x5e, 0x1f, 0x8d, 0x5e, 0x1d, 0x6f, 0x0d, 0xcd, 0x0a, 0xea, 0x40,
	0xe3, 0xd0, 0xe1, 0x66, 0xb5, 0x88, 0xef, 0x6c, 0x9b, 0x35, 0x15, 0xdf, 0xd9, 0x36, 0xeb, 0xdc,
	0x3c, 0xf8, 0x61, 0xb4, 0xf7, 0xbd, 0xd9, 0x40, 0x6d, 0xa8, 0x7f, 0xfb, 0xd3, 0xf1, 0x81, 0xd9,
	0x14, 0xd6, 0x68, 0x74, 0x64, 0xb6, 0xb8, 0xe5, 0x8c, 0x9c, 0x03, 0xb3, 0x8d, 0x00, 0x9a, 0xe3,
	0x63, 0xf7, 0xd0, 0xf9, 0xce, 0xec, 0xa8, 0xfa, 0xcd, 0x1d, 0x13, 0xb8, 0x79, 0x72, 0xe8, 0x1c,
	0x3f, 0x37, 0x0d, 0x8e, 0x38, 0x91, 0xe1, 0x6e, 0x6e, 0x6f, 0x0d, 0xcd, 0x85, 0xdc, 0xde, 0xd9,
	0x36, 0x17, 0x87, 0x7f, 0x57, 0xc1, 0x78, 0x37, 0xff, 0xcf, 0x03, 0x7d, 0x0d, 0x0d, 0x71, 0xe7,
	0x50, 0xae, 0xea, 0x5b, 0x3f, 0x07, 0xbd, 0x8f, 0xef, 0xc8, 0x28, 0x82, 0x76, 0xa1, 0x21, 0x2e,
	0x4a, 0xb9, 0x5a, 0xbf, 0x3b, 0xbd, 0x9e, 0x9e, 0xb9, 0xa1, 0xce, 0x5d, 0x68, 0xed, 0x63, 0xca,
	0x48, 0x92, 0xa1, 0x47, 0x3a, 0x6c, 0x2e, 0xa0, 0x7f, 0x2d, 0xdf, 0x07, 0x43, 0x93, 0x06, 0xca,
	0xcf, 0x79, 0x5b, 0x5e, 0x45, 0x97, 0xbb, 0x94, 0xf4, 0x06, 0x16, 0x4a, 0xdb, 0x47, 0xab, 0xa5,
	0x7b, 0x56, 0x56, 0x51, 0xef, 0xf1, 0xdd, 0x49, 0xd9, 0xeb, 0xb4, 0x29, 0x92, 0x5b, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x0f, 0xd5, 0xb9, 0x2e, 0xdd, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketstoreClient is the client API for Marketstore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketstoreClient interface {
	Query(ctx context.Context, in *MultiQueryRequest, opts ...grpc.CallOption) (*MultiQueryResponse, error)
	Write(ctx context.Context, in *MultiWriteRequest, opts ...grpc.CallOption) (*MultiServerResponse, error)
	Destroy(ctx context.Context, in *MultiKeyRequest, opts ...grpc.CallOption) (*MultiServerResponse, error)
	ListSymbols(ctx context.Context, in *ListSymbolsRequest, opts ...grpc.CallOption) (*ListSymbolsResponse, error)
	ServerVersion(ctx context.Context, in *ServerVersionRequest, opts ...grpc.CallOption) (*ServerVersionResponse, error)
}

type marketstoreClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketstoreClient(cc grpc.ClientConnInterface) MarketstoreClient {
	return &marketstoreClient{cc}
}

func (c *marketstoreClient) Query(ctx context.Context, in *MultiQueryRequest, opts ...grpc.CallOption) (*MultiQueryResponse, error) {
	out := new(MultiQueryResponse)
	err := c.cc.Invoke(ctx, "/proto.Marketstore/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketstoreClient) Write(ctx context.Context, in *MultiWriteRequest, opts ...grpc.CallOption) (*MultiServerResponse, error) {
	out := new(MultiServerResponse)
	err := c.cc.Invoke(ctx, "/proto.Marketstore/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketstoreClient) Destroy(ctx context.Context, in *MultiKeyRequest, opts ...grpc.CallOption) (*MultiServerResponse, error) {
	out := new(MultiServerResponse)
	err := c.cc.Invoke(ctx, "/proto.Marketstore/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketstoreClient) ListSymbols(ctx context.Context, in *ListSymbolsRequest, opts ...grpc.CallOption) (*ListSymbolsResponse, error) {
	out := new(ListSymbolsResponse)
	err := c.cc.Invoke(ctx, "/proto.Marketstore/ListSymbols", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketstoreClient) ServerVersion(ctx context.Context, in *ServerVersionRequest, opts ...grpc.CallOption) (*ServerVersionResponse, error) {
	out := new(ServerVersionResponse)
	err := c.cc.Invoke(ctx, "/proto.Marketstore/ServerVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketstoreServer is the server API for Marketstore service.
type MarketstoreServer interface {
	Query(context.Context, *MultiQueryRequest) (*MultiQueryResponse, error)
	Write(context.Context, *MultiWriteRequest) (*MultiServerResponse, error)
	Destroy(context.Context, *MultiKeyRequest) (*MultiServerResponse, error)
	ListSymbols(context.Context, *ListSymbolsRequest) (*ListSymbolsResponse, error)
	ServerVersion(context.Context, *ServerVersionRequest) (*ServerVersionResponse, error)
}

// UnimplementedMarketstoreServer can be embedded to have forward compatible implementations.
type UnimplementedMarketstoreServer struct {
}

func (*UnimplementedMarketstoreServer) Query(ctx context.Context, req *MultiQueryRequest) (*MultiQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedMarketstoreServer) Write(ctx context.Context, req *MultiWriteRequest) (*MultiServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (*UnimplementedMarketstoreServer) Destroy(ctx context.Context, req *MultiKeyRequest) (*MultiServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (*UnimplementedMarketstoreServer) ListSymbols(ctx context.Context, req *ListSymbolsRequest) (*ListSymbolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSymbols not implemented")
}
func (*UnimplementedMarketstoreServer) ServerVersion(ctx context.Context, req *ServerVersionRequest) (*ServerVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerVersion not implemented")
}

func RegisterMarketstoreServer(s *grpc.Server, srv MarketstoreServer) {
	s.RegisterService(&_Marketstore_serviceDesc, srv)
}

func _Marketstore_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketstoreServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Marketstore/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketstoreServer).Query(ctx, req.(*MultiQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketstore_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketstoreServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Marketstore/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketstoreServer).Write(ctx, req.(*MultiWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketstore_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketstoreServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Marketstore/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketstoreServer).Destroy(ctx, req.(*MultiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketstore_ListSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketstoreServer).ListSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Marketstore/ListSymbols",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketstoreServer).ListSymbols(ctx, req.(*ListSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketstore_ServerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketstoreServer).ServerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Marketstore/ServerVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketstoreServer).ServerVersion(ctx, req.(*ServerVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Marketstore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Marketstore",
	HandlerType: (*MarketstoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Marketstore_Query_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Marketstore_Write_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Marketstore_Destroy_Handler,
		},
		{
			MethodName: "ListSymbols",
			Handler:    _Marketstore_ListSymbols_Handler,
		},
		{
			MethodName: "ServerVersion",
			Handler:    _Marketstore_ServerVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketstore.proto",
}
