// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replication.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Every message written to the WAL is prepended by the MID, indicating what type of message follows. The MID is structured on-disk:
type MessageID int32

const (
	MessageID_TRANSACTION_GROUP MessageID = 0
	MessageID_TRANSACTION_INFO  MessageID = 1
	MessageID_WAL_STATUS        MessageID = 2
)

var MessageID_name = map[int32]string{
	0: "TRANSACTION_GROUP",
	1: "TRANSACTION_INFO",
	2: "WAL_STATUS",
}

var MessageID_value = map[string]int32{
	"TRANSACTION_GROUP": 0,
	"TRANSACTION_INFO":  1,
	"WAL_STATUS":        2,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{0}
}

type DestinationID int32

const (
	DestinationID_WAL           DestinationID = 0
	DestinationID_PRIMARY_STORE DestinationID = 1
)

var DestinationID_name = map[int32]string{
	0: "WAL",
	1: "PRIMARY_STORE",
}

var DestinationID_value = map[string]int32{
	"WAL":           0,
	"PRIMARY_STORE": 1,
}

func (x DestinationID) String() string {
	return proto.EnumName(DestinationID_name, int32(x))
}

func (DestinationID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{1}
}

// Note: Commit intent state is for future multi-party commit support. Typical processes will only use states 0 and 2
type TIStatus int32

const (
	TIStatus_PREPARING_TO_COMMIT TIStatus = 0
	TIStatus_COMMIT_INTENT_SENT  TIStatus = 1
	TIStatus_COMMIT_COMPLETE     TIStatus = 2
)

var TIStatus_name = map[int32]string{
	0: "PREPARING_TO_COMMIT",
	1: "COMMIT_INTENT_SENT",
	2: "COMMIT_COMPLETE",
}

var TIStatus_value = map[string]int32{
	"PREPARING_TO_COMMIT": 0,
	"COMMIT_INTENT_SENT":  1,
	"COMMIT_COMPLETE":     2,
}

func (x TIStatus) String() string {
	return proto.EnumName(TIStatus_name, int32(x))
}

func (TIStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{2}
}

type RecordType int32

const (
	RecordType_FIXED RecordType = 0
	// for variable-length record
	RecordType_VARIABLE RecordType = 1
	RecordType_NO_TYPE  RecordType = 2
)

var RecordType_name = map[int32]string{
	0: "FIXED",
	1: "VARIABLE",
	2: "NO_TYPE",
}

var RecordType_value = map[string]int32{
	"FIXED":    0,
	"VARIABLE": 1,
	"NO_TYPE":  2,
}

func (x RecordType) String() string {
	return proto.EnumName(RecordType_name, int32(x))
}

func (RecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{3}
}

type FileStatus int32

const (
	// Actively in use or not closed programatically
	FileStatus_IN_USE FileStatus = 0
	// Closed (no process is using file)
	FileStatus_CLOSED FileStatus = 1
)

var FileStatus_name = map[int32]string{
	0: "IN_USE",
	1: "CLOSED",
}

var FileStatus_value = map[string]int32{
	"IN_USE": 0,
	"CLOSED": 1,
}

func (x FileStatus) String() string {
	return proto.EnumName(FileStatus_name, int32(x))
}

func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{4}
}

type ReplayState int32

const (
	// Not yet processed for replay
	ReplayState_NOT_YET_PROCESSED ReplayState = 0
	// Replayed successfully
	ReplayState_REPLAYED ReplayState = 1
	// Replay in process
	ReplayState_REPLAY_IN_PROCESS ReplayState = 2
)

var ReplayState_name = map[int32]string{
	0: "NOT_YET_PROCESSED",
	1: "REPLAYED",
	2: "REPLAY_IN_PROCESS",
}

var ReplayState_value = map[string]int32{
	"NOT_YET_PROCESSED": 0,
	"REPLAYED":          1,
	"REPLAY_IN_PROCESS": 2,
}

func (x ReplayState) String() string {
	return proto.EnumName(ReplayState_name, int32(x))
}

func (ReplayState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{5}
}

type WriteAheadLog struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteAheadLog) Reset()         { *m = WriteAheadLog{} }
func (m *WriteAheadLog) String() string { return proto.CompactTextString(m) }
func (*WriteAheadLog) ProtoMessage()    {}
func (*WriteAheadLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{0}
}

func (m *WriteAheadLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteAheadLog.Unmarshal(m, b)
}
func (m *WriteAheadLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteAheadLog.Marshal(b, m, deterministic)
}
func (m *WriteAheadLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteAheadLog.Merge(m, src)
}
func (m *WriteAheadLog) XXX_Size() int {
	return xxx_messageInfo_WriteAheadLog.Size(m)
}
func (m *WriteAheadLog) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteAheadLog.DiscardUnknown(m)
}

var xxx_messageInfo_WriteAheadLog proto.InternalMessageInfo

// decided not to use the protobuf definition of WAL as currently WAL message is serialized to an original binary in marketstore
// and it's easier to directly send it without using protobuf
type WALMessage struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WALMessage) Reset()         { *m = WALMessage{} }
func (m *WALMessage) String() string { return proto.CompactTextString(m) }
func (*WALMessage) ProtoMessage()    {}
func (*WALMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{1}
}

func (m *WALMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WALMessage.Unmarshal(m, b)
}
func (m *WALMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WALMessage.Marshal(b, m, deterministic)
}
func (m *WALMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WALMessage.Merge(m, src)
}
func (m *WALMessage) XXX_Size() int {
	return xxx_messageInfo_WALMessage.Size(m)
}
func (m *WALMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WALMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WALMessage proto.InternalMessageInfo

func (m *WALMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// A transaction info message marks the write status of transactions. It is used in two situations:
// When a TG is written to the WAL and when the BW writes a TG to the primary store. The on-disk format of a TI is
type TransactionInfo struct {
	TransactionGroupId   int64         `protobuf:"varint,1,opt,name=transaction_group_id,json=transactionGroupId,proto3" json:"transaction_group_id,omitempty"`
	DestinationId        DestinationID `protobuf:"varint,2,opt,name=destination_id,json=destinationId,proto3,enum=proto.DestinationID" json:"destination_id,omitempty"`
	Status               TIStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=proto.TIStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransactionInfo) Reset()         { *m = TransactionInfo{} }
func (m *TransactionInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionInfo) ProtoMessage()    {}
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{2}
}

func (m *TransactionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInfo.Unmarshal(m, b)
}
func (m *TransactionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInfo.Marshal(b, m, deterministic)
}
func (m *TransactionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInfo.Merge(m, src)
}
func (m *TransactionInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionInfo.Size(m)
}
func (m *TransactionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInfo proto.InternalMessageInfo

func (m *TransactionInfo) GetTransactionGroupId() int64 {
	if m != nil {
		return m.TransactionGroupId
	}
	return 0
}

func (m *TransactionInfo) GetDestinationId() DestinationID {
	if m != nil {
		return m.DestinationId
	}
	return DestinationID_WAL
}

func (m *TransactionInfo) GetStatus() TIStatus {
	if m != nil {
		return m.Status
	}
	return TIStatus_PREPARING_TO_COMMIT
}

// Transaction Group (TG): A group of data committed at one time to WAL and primary store
// Each TG is composed of some number of WTSets and is the smallest unit of data committed to disk.
// A TG has an ID that is used to verify whether the TG has been successfully written. A TG has the following structure:
type TransactionGroup struct {
	// The length of the TG data for this TGID, starting with the TGID and excluding the checksum
	Length int64 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	// A "locally unique" transaction group identifier, can be a clock value
	// This ID will be used for the position that indicates that replication is done until that point
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// The count of WTSets in this TG
	WtCount int64 `protobuf:"varint,3,opt,name=wt_count,json=wtCount,proto3" json:"wt_count,omitempty"`
	// The contents of the WTSets
	WtGroup []*WriteTransactionSet `protobuf:"bytes,4,rep,name=wt_group,json=wtGroup,proto3" json:"wt_group,omitempty"`
	// MD5 checksum of the TG contents prior to the checksum
	Checksum             []byte   `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionGroup) Reset()         { *m = TransactionGroup{} }
func (m *TransactionGroup) String() string { return proto.CompactTextString(m) }
func (*TransactionGroup) ProtoMessage()    {}
func (*TransactionGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{3}
}

func (m *TransactionGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionGroup.Unmarshal(m, b)
}
func (m *TransactionGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionGroup.Marshal(b, m, deterministic)
}
func (m *TransactionGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionGroup.Merge(m, src)
}
func (m *TransactionGroup) XXX_Size() int {
	return xxx_messageInfo_TransactionGroup.Size(m)
}
func (m *TransactionGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionGroup proto.InternalMessageInfo

func (m *TransactionGroup) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *TransactionGroup) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransactionGroup) GetWtCount() int64 {
	if m != nil {
		return m.WtCount
	}
	return 0
}

func (m *TransactionGroup) GetWtGroup() []*WriteTransactionSet {
	if m != nil {
		return m.WtGroup
	}
	return nil
}

func (m *TransactionGroup) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

type WriteTransactionSet struct {
	// Direct or Indirect IO (for variable or fixed length records)
	RecordType RecordType `protobuf:"varint,1,opt,name=record_type,json=recordType,proto3,enum=proto.RecordType" json:"record_type,omitempty"`
	// Length of FilePath string
	FpLen int32 `protobuf:"varint,2,opt,name=fp_len,json=fpLen,proto3" json:"fp_len,omitempty"`
	// FilePath is relative to the root directory, string is ASCII encoded without a trailing null
	Filepath string `protobuf:"bytes,3,opt,name=filepath,proto3" json:"filepath,omitempty"`
	// Year associated with this file
	Year int32 `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	// Number of intervals per day in this file
	Intervals int64 `protobuf:"varint,5,opt,name=intervals,proto3" json:"intervals,omitempty"`
	// Count of records in this WT set
	RecordCount int32 `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	// Length of each data element in this set in bytes, excluding the index
	DataOnlyLen int64 `protobuf:"varint,7,opt,name=data_only_len,json=dataOnlyLen,proto3" json:"data_only_len,omitempty"`
	// Interval Index based on the intervals/day of the target file
	Index []int64 `protobuf:"varint,8,rep,packed,name=index,proto3" json:"index,omitempty"`
	// Data bytes
	Buffer               []byte   `protobuf:"bytes,9,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteTransactionSet) Reset()         { *m = WriteTransactionSet{} }
func (m *WriteTransactionSet) String() string { return proto.CompactTextString(m) }
func (*WriteTransactionSet) ProtoMessage()    {}
func (*WriteTransactionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{4}
}

func (m *WriteTransactionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteTransactionSet.Unmarshal(m, b)
}
func (m *WriteTransactionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteTransactionSet.Marshal(b, m, deterministic)
}
func (m *WriteTransactionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteTransactionSet.Merge(m, src)
}
func (m *WriteTransactionSet) XXX_Size() int {
	return xxx_messageInfo_WriteTransactionSet.Size(m)
}
func (m *WriteTransactionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteTransactionSet.DiscardUnknown(m)
}

var xxx_messageInfo_WriteTransactionSet proto.InternalMessageInfo

func (m *WriteTransactionSet) GetRecordType() RecordType {
	if m != nil {
		return m.RecordType
	}
	return RecordType_FIXED
}

func (m *WriteTransactionSet) GetFpLen() int32 {
	if m != nil {
		return m.FpLen
	}
	return 0
}

func (m *WriteTransactionSet) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *WriteTransactionSet) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *WriteTransactionSet) GetIntervals() int64 {
	if m != nil {
		return m.Intervals
	}
	return 0
}

func (m *WriteTransactionSet) GetRecordCount() int32 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *WriteTransactionSet) GetDataOnlyLen() int64 {
	if m != nil {
		return m.DataOnlyLen
	}
	return 0
}

func (m *WriteTransactionSet) GetIndex() []int64 {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *WriteTransactionSet) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type WALStatus struct {
	FileStatus  FileStatus  `protobuf:"varint,1,opt,name=file_status,json=fileStatus,proto3,enum=proto.FileStatus" json:"file_status,omitempty"`
	ReplayState ReplayState `protobuf:"varint,2,opt,name=replay_state,json=replayState,proto3,enum=proto.ReplayState" json:"replay_state,omitempty"`
	// PID of the process using this WAL file
	OwningPid            int64    `protobuf:"varint,3,opt,name=owning_pid,json=owningPid,proto3" json:"owning_pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WALStatus) Reset()         { *m = WALStatus{} }
func (m *WALStatus) String() string { return proto.CompactTextString(m) }
func (*WALStatus) ProtoMessage()    {}
func (*WALStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{5}
}

func (m *WALStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WALStatus.Unmarshal(m, b)
}
func (m *WALStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WALStatus.Marshal(b, m, deterministic)
}
func (m *WALStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WALStatus.Merge(m, src)
}
func (m *WALStatus) XXX_Size() int {
	return xxx_messageInfo_WALStatus.Size(m)
}
func (m *WALStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_WALStatus.DiscardUnknown(m)
}

var xxx_messageInfo_WALStatus proto.InternalMessageInfo

func (m *WALStatus) GetFileStatus() FileStatus {
	if m != nil {
		return m.FileStatus
	}
	return FileStatus_IN_USE
}

func (m *WALStatus) GetReplayState() ReplayState {
	if m != nil {
		return m.ReplayState
	}
	return ReplayState_NOT_YET_PROCESSED
}

func (m *WALStatus) GetOwningPid() int64 {
	if m != nil {
		return m.OwningPid
	}
	return 0
}

type GetWALStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWALStreamRequest) Reset()         { *m = GetWALStreamRequest{} }
func (m *GetWALStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GetWALStreamRequest) ProtoMessage()    {}
func (*GetWALStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{6}
}

func (m *GetWALStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWALStreamRequest.Unmarshal(m, b)
}
func (m *GetWALStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWALStreamRequest.Marshal(b, m, deterministic)
}
func (m *GetWALStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWALStreamRequest.Merge(m, src)
}
func (m *GetWALStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GetWALStreamRequest.Size(m)
}
func (m *GetWALStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWALStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWALStreamRequest proto.InternalMessageInfo

// 空のmessage
type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{7}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type GreetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{8}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreetMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetMessage) Reset()         { *m = GreetMessage{} }
func (m *GreetMessage) String() string { return proto.CompactTextString(m) }
func (*GreetMessage) ProtoMessage()    {}
func (*GreetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{9}
}

func (m *GreetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetMessage.Unmarshal(m, b)
}
func (m *GreetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetMessage.Marshal(b, m, deterministic)
}
func (m *GreetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetMessage.Merge(m, src)
}
func (m *GreetMessage) XXX_Size() int {
	return xxx_messageInfo_GreetMessage.Size(m)
}
func (m *GreetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GreetMessage proto.InternalMessageInfo

func (m *GreetMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RoomRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRequest) Reset()         { *m = RoomRequest{} }
func (m *RoomRequest) String() string { return proto.CompactTextString(m) }
func (*RoomRequest) ProtoMessage()    {}
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{10}
}

func (m *RoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRequest.Unmarshal(m, b)
}
func (m *RoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRequest.Marshal(b, m, deterministic)
}
func (m *RoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRequest.Merge(m, src)
}
func (m *RoomRequest) XXX_Size() int {
	return xxx_messageInfo_RoomRequest.Size(m)
}
func (m *RoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRequest proto.InternalMessageInfo

func (m *RoomRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoomInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageCount         int32    `protobuf:"varint,2,opt,name=messageCount,proto3" json:"messageCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{11}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomInfo) GetMessageCount() int32 {
	if m != nil {
		return m.MessageCount
	}
	return 0
}

type RoomList struct {
	Rooms                []*RoomInfo `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomList) Reset()         { *m = RoomList{} }
func (m *RoomList) String() string { return proto.CompactTextString(m) }
func (*RoomList) ProtoMessage()    {}
func (*RoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{12}
}

func (m *RoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomList.Unmarshal(m, b)
}
func (m *RoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomList.Marshal(b, m, deterministic)
}
func (m *RoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomList.Merge(m, src)
}
func (m *RoomList) XXX_Size() int {
	return xxx_messageInfo_RoomList.Size(m)
}
func (m *RoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomList.DiscardUnknown(m)
}

var xxx_messageInfo_RoomList proto.InternalMessageInfo

func (m *RoomList) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type SendRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{13}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SendRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResult) Reset()         { *m = SendResult{} }
func (m *SendResult) String() string { return proto.CompactTextString(m) }
func (*SendResult) ProtoMessage()    {}
func (*SendResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{14}
}

func (m *SendResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResult.Unmarshal(m, b)
}
func (m *SendResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResult.Marshal(b, m, deterministic)
}
func (m *SendResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResult.Merge(m, src)
}
func (m *SendResult) XXX_Size() int {
	return xxx_messageInfo_SendResult.Size(m)
}
func (m *SendResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResult.DiscardUnknown(m)
}

var xxx_messageInfo_SendResult proto.InternalMessageInfo

func (m *SendResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type MessagesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesRequest) Reset()         { *m = MessagesRequest{} }
func (m *MessagesRequest) String() string { return proto.CompactTextString(m) }
func (*MessagesRequest) ProtoMessage()    {}
func (*MessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{15}
}

func (m *MessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesRequest.Unmarshal(m, b)
}
func (m *MessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesRequest.Marshal(b, m, deterministic)
}
func (m *MessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesRequest.Merge(m, src)
}
func (m *MessagesRequest) XXX_Size() int {
	return xxx_messageInfo_MessagesRequest.Size(m)
}
func (m *MessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesRequest proto.InternalMessageInfo

func (m *MessagesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0454e9e09fb71a, []int{16}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.MessageID", MessageID_name, MessageID_value)
	proto.RegisterEnum("proto.DestinationID", DestinationID_name, DestinationID_value)
	proto.RegisterEnum("proto.TIStatus", TIStatus_name, TIStatus_value)
	proto.RegisterEnum("proto.RecordType", RecordType_name, RecordType_value)
	proto.RegisterEnum("proto.FileStatus", FileStatus_name, FileStatus_value)
	proto.RegisterEnum("proto.ReplayState", ReplayState_name, ReplayState_value)
	proto.RegisterType((*WriteAheadLog)(nil), "proto.WriteAheadLog")
	proto.RegisterType((*WALMessage)(nil), "proto.WALMessage")
	proto.RegisterType((*TransactionInfo)(nil), "proto.TransactionInfo")
	proto.RegisterType((*TransactionGroup)(nil), "proto.TransactionGroup")
	proto.RegisterType((*WriteTransactionSet)(nil), "proto.WriteTransactionSet")
	proto.RegisterType((*WALStatus)(nil), "proto.WALStatus")
	proto.RegisterType((*GetWALStreamRequest)(nil), "proto.GetWALStreamRequest")
	proto.RegisterType((*Null)(nil), "proto.Null")
	proto.RegisterType((*GreetRequest)(nil), "proto.GreetRequest")
	proto.RegisterType((*GreetMessage)(nil), "proto.GreetMessage")
	proto.RegisterType((*RoomRequest)(nil), "proto.RoomRequest")
	proto.RegisterType((*RoomInfo)(nil), "proto.RoomInfo")
	proto.RegisterType((*RoomList)(nil), "proto.RoomList")
	proto.RegisterType((*SendRequest)(nil), "proto.SendRequest")
	proto.RegisterType((*SendResult)(nil), "proto.SendResult")
	proto.RegisterType((*MessagesRequest)(nil), "proto.MessagesRequest")
	proto.RegisterType((*Message)(nil), "proto.Message")
}

func init() {
	proto.RegisterFile("replication.proto", fileDescriptor_ed0454e9e09fb71a)
}

var fileDescriptor_ed0454e9e09fb71a = []byte{
	// 982 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xe3, 0xe6, 0xef, 0x24, 0x4d, 0xdd, 0x69, 0xb7, 0x84, 0x8a, 0x95, 0xba, 0xd6, 0x02,
	0x55, 0x91, 0x56, 0x25, 0x68, 0xe1, 0x02, 0x09, 0x64, 0x52, 0x37, 0x58, 0x38, 0xb6, 0x35, 0x76,
	0x29, 0xbd, 0x1a, 0x79, 0xe3, 0x49, 0x6a, 0xe1, 0xd8, 0xc6, 0x9e, 0x50, 0xf2, 0x20, 0x3c, 0x01,
	0x37, 0xf0, 0x14, 0xbc, 0x1a, 0x9a, 0xf1, 0x38, 0x49, 0xab, 0xdd, 0x2b, 0xae, 0x7c, 0xfe, 0xe7,
	0x3b, 0xdf, 0x9c, 0x33, 0x86, 0xa3, 0x82, 0xe6, 0x49, 0x3c, 0x0b, 0x59, 0x9c, 0xa5, 0x6f, 0xf2,
	0x22, 0x63, 0x19, 0x6a, 0x8a, 0x8f, 0x7e, 0x08, 0x07, 0x77, 0x45, 0xcc, 0xa8, 0xf1, 0x40, 0xc3,
	0xc8, 0xce, 0x16, 0xfa, 0x67, 0x00, 0x77, 0x86, 0x3d, 0xa5, 0x65, 0x19, 0x2e, 0x28, 0x1a, 0x42,
	0x7b, 0x59, 0x89, 0x43, 0xe5, 0x5c, 0xb9, 0xe8, 0xe3, 0x5a, 0xd5, 0xff, 0x51, 0xe0, 0x30, 0x28,
	0xc2, 0xb4, 0x0c, 0x67, 0xbc, 0xaa, 0x95, 0xce, 0x33, 0x74, 0x05, 0x27, 0x6c, 0x6b, 0x22, 0x8b,
	0x22, 0x5b, 0xe5, 0x24, 0x8e, 0x44, 0xaa, 0x8a, 0xd1, 0x8e, 0x6f, 0xc2, 0x5d, 0x56, 0x84, 0xbe,
	0x85, 0x41, 0x44, 0x4b, 0x16, 0xa7, 0x02, 0x1a, 0x8f, 0x6d, 0x9c, 0x2b, 0x17, 0x83, 0xd1, 0x49,
	0x85, 0xf2, 0xcd, 0xf5, 0xd6, 0x69, 0x5d, 0xe3, 0x83, 0x9d, 0x58, 0x2b, 0x42, 0x9f, 0x43, 0xab,
	0x64, 0x21, 0x5b, 0x95, 0x43, 0x55, 0x24, 0x1d, 0xca, 0xa4, 0xc0, 0xf2, 0x85, 0x19, 0x4b, 0xb7,
	0xfe, 0xb7, 0x02, 0x5a, 0xf0, 0xec, 0x70, 0x74, 0x0a, 0xad, 0x84, 0xa6, 0x0b, 0xf6, 0x20, 0xe1,
	0x49, 0x0d, 0x0d, 0xa0, 0x21, 0x61, 0xa8, 0xb8, 0x11, 0x47, 0xe8, 0x63, 0xe8, 0x3c, 0x32, 0x32,
	0xcb, 0x56, 0x29, 0x13, 0xe7, 0xa8, 0xb8, 0xfd, 0xc8, 0xc6, 0x5c, 0x45, 0x6f, 0x85, 0x4b, 0xb4,
	0x39, 0xdc, 0x3f, 0x57, 0x2f, 0x7a, 0xa3, 0x33, 0x09, 0x41, 0x70, 0xba, 0x73, 0xa4, 0x4f, 0x19,
	0x4f, 0xab, 0x4e, 0x3e, 0x83, 0xce, 0xec, 0x81, 0xce, 0x7e, 0x2d, 0x57, 0xcb, 0x61, 0x53, 0xb0,
	0xba, 0xd1, 0xf5, 0xbf, 0x1a, 0x70, 0xfc, 0x9e, 0x64, 0x34, 0x82, 0x5e, 0x41, 0x67, 0x59, 0x11,
	0x11, 0xb6, 0xce, 0xab, 0xcb, 0x18, 0x8c, 0x8e, 0xe4, 0x69, 0x58, 0x78, 0x82, 0x75, 0x4e, 0x31,
	0x14, 0x1b, 0x19, 0xbd, 0x80, 0xd6, 0x3c, 0x27, 0x09, 0x4d, 0x45, 0x37, 0x4d, 0xdc, 0x9c, 0xe7,
	0x36, 0x4d, 0xf9, 0xf1, 0xf3, 0x38, 0xa1, 0x79, 0xc8, 0x1e, 0x44, 0x43, 0x5d, 0xbc, 0xd1, 0x11,
	0x82, 0xfd, 0x35, 0x0d, 0x8b, 0xe1, 0xbe, 0x48, 0x10, 0x32, 0xfa, 0x04, 0xba, 0x71, 0xca, 0x68,
	0xf1, 0x7b, 0x98, 0x94, 0x02, 0xaf, 0x8a, 0xb7, 0x06, 0xf4, 0x0a, 0xfa, 0x12, 0x58, 0x45, 0x51,
	0x4b, 0x64, 0x4a, 0xb0, 0x15, 0x4d, 0x3a, 0x1c, 0x44, 0x21, 0x0b, 0x49, 0x96, 0x26, 0x6b, 0x01,
	0xa7, 0x2d, 0x8a, 0xf4, 0xb8, 0xd1, 0x4d, 0x93, 0x35, 0x07, 0x75, 0x02, 0xcd, 0x38, 0x8d, 0xe8,
	0x1f, 0xc3, 0xce, 0xb9, 0x7a, 0xa1, 0xe2, 0x4a, 0xe1, 0x77, 0xf4, 0x6e, 0x35, 0x9f, 0xd3, 0x62,
	0xd8, 0x15, 0x3c, 0x49, 0x4d, 0xff, 0x53, 0x81, 0xee, 0x9d, 0x61, 0x57, 0xd7, 0xcc, 0xb9, 0xe1,
	0x0d, 0x10, 0x39, 0x0c, 0x4f, 0xb9, 0xb9, 0x89, 0x13, 0x2a, 0xc7, 0x01, 0xe6, 0x1b, 0x19, 0xbd,
	0xe5, 0xb0, 0xf3, 0x24, 0x5c, 0x8b, 0x2c, 0x2a, 0xc7, 0x0e, 0x6d, 0x08, 0xe5, 0x2e, 0x1e, 0x4a,
	0x79, 0x2b, 0x1b, 0x05, 0xbd, 0x04, 0xc8, 0x1e, 0xd3, 0x38, 0x5d, 0x90, 0x3c, 0x8e, 0xe4, 0x38,
	0x74, 0x2b, 0x8b, 0x17, 0x47, 0xfa, 0x0b, 0x38, 0x9e, 0x50, 0x26, 0x90, 0x15, 0x34, 0x5c, 0x62,
	0xfa, 0xdb, 0x8a, 0x96, 0x4c, 0x6f, 0xc1, 0xbe, 0xb3, 0x4a, 0x12, 0x5d, 0x87, 0xfe, 0xa4, 0xa0,
	0x94, 0x49, 0x3b, 0x67, 0x3b, 0x0d, 0x97, 0xd5, 0x6d, 0x76, 0xb1, 0x90, 0xf5, 0x73, 0x19, 0x53,
	0x6f, 0xa0, 0x06, 0xea, 0xb2, 0x5c, 0xc8, 0x10, 0x2e, 0xea, 0x2f, 0xa1, 0x87, 0xb3, 0xac, 0x2e,
	0x2e, 0xe7, 0xb5, 0xf2, 0x37, 0xe2, 0x48, 0xff, 0x0e, 0x3a, 0xdc, 0x2d, 0x16, 0xf2, 0x99, 0x0f,
	0xe9, 0xd0, 0x97, 0xfb, 0x2b, 0x6e, 0x46, 0xce, 0xc5, 0x13, 0x9b, 0xfe, 0x65, 0x95, 0x6f, 0xc7,
	0x25, 0x43, 0x9f, 0x42, 0xb3, 0xc8, 0xb2, 0x25, 0xe7, 0x94, 0x4f, 0x77, 0xbd, 0x60, 0x75, 0x7d,
	0x5c, 0x79, 0xf5, 0x9f, 0xa0, 0xe7, 0xd3, 0x34, 0xfa, 0x00, 0xa2, 0x4d, 0x9b, 0x8d, 0x6d, 0x9b,
	0xfc, 0x61, 0x99, 0x65, 0x29, 0xa3, 0x72, 0xa9, 0xba, 0xb8, 0x56, 0xf5, 0xd7, 0x00, 0x55, 0xb1,
	0x72, 0x95, 0x30, 0x3e, 0x01, 0x85, 0x90, 0x44, 0xbd, 0x0e, 0x96, 0x9a, 0xfe, 0x0a, 0x0e, 0x25,
	0x43, 0xe5, 0x87, 0x88, 0x98, 0x40, 0xbb, 0x26, 0xf1, 0x7f, 0x21, 0xba, 0xfc, 0x11, 0xba, 0xb2,
	0x90, 0x75, 0x8d, 0x5e, 0xc0, 0x51, 0x80, 0x0d, 0xc7, 0x37, 0xc6, 0x81, 0xe5, 0x3a, 0x64, 0x82,
	0xdd, 0x5b, 0x4f, 0xdb, 0x43, 0x27, 0xa0, 0xed, 0x9a, 0x2d, 0xe7, 0xc6, 0xd5, 0x14, 0x34, 0x10,
	0x8f, 0x29, 0xf1, 0x03, 0x23, 0xb8, 0xf5, 0xb5, 0xc6, 0xe5, 0x17, 0x70, 0xf0, 0xe4, 0x45, 0x43,
	0x6d, 0x50, 0xef, 0x0c, 0x5b, 0xdb, 0x43, 0x47, 0x70, 0xe0, 0x61, 0x6b, 0x6a, 0xe0, 0x7b, 0xe2,
	0x07, 0x2e, 0x36, 0x35, 0xe5, 0xd2, 0x83, 0x4e, 0xfd, 0x92, 0xa1, 0x8f, 0xe0, 0xd8, 0xc3, 0xa6,
	0x67, 0x60, 0xcb, 0x99, 0x90, 0xc0, 0x25, 0x63, 0x77, 0x3a, 0xb5, 0x02, 0x6d, 0x0f, 0x9d, 0x02,
	0xaa, 0x64, 0x62, 0x39, 0x81, 0xe9, 0x04, 0xc4, 0x37, 0x9d, 0x40, 0x53, 0xd0, 0x31, 0x1c, 0x4a,
	0xfb, 0xd8, 0x9d, 0x7a, 0xb6, 0x19, 0x98, 0x5a, 0xe3, 0x72, 0x04, 0xb0, 0x7d, 0x2a, 0x50, 0x17,
	0x9a, 0x37, 0xd6, 0x2f, 0xe6, 0xb5, 0xb6, 0x87, 0xfa, 0xd0, 0xf9, 0xd9, 0xc0, 0x96, 0xf1, 0x83,
	0x6d, 0x6a, 0x0a, 0xea, 0x41, 0xdb, 0x71, 0x49, 0x70, 0xef, 0xf1, 0x9c, 0xd7, 0x00, 0xdb, 0x15,
	0x42, 0x00, 0x2d, 0xcb, 0x21, 0xb7, 0xbe, 0xa9, 0xed, 0x71, 0x79, 0x6c, 0xbb, 0xbe, 0x79, 0xad,
	0x29, 0x97, 0x16, 0xf4, 0x76, 0x76, 0x86, 0x93, 0xe4, 0xb8, 0x01, 0xb9, 0x37, 0x03, 0xe2, 0x61,
	0x77, 0x6c, 0xfa, 0x7e, 0x7d, 0x0c, 0x36, 0x3d, 0xdb, 0xb8, 0xe7, 0x39, 0x3c, 0xa8, 0xd2, 0x88,
	0xe5, 0xd4, 0x61, 0x5a, 0x63, 0xf4, 0xaf, 0x52, 0xd5, 0x92, 0xbf, 0x2b, 0xf4, 0x3d, 0xf4, 0x77,
	0x77, 0x0a, 0xd5, 0x4f, 0xec, 0x7b, 0x16, 0xed, 0xac, 0x5e, 0xfa, 0xed, 0x1f, 0xec, 0x4a, 0x41,
	0x5f, 0x57, 0xd3, 0x59, 0xcf, 0x42, 0xbd, 0xe3, 0x3b, 0x13, 0xbb, 0xc9, 0xdb, 0x0e, 0xde, 0x85,
	0x82, 0xbe, 0x81, 0xde, 0x64, 0xb3, 0x87, 0x25, 0x3a, 0x95, 0x31, 0xcf, 0xc6, 0xee, 0x6c, 0xf0,
	0xd4, 0x7e, 0xa5, 0xbc, 0x6b, 0x09, 0xc3, 0x57, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xe0,
	0x86, 0xdb, 0x76, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicationClient interface {
	GetWALStream(ctx context.Context, in *GetWALStreamRequest, opts ...grpc.CallOption) (Replication_GetWALStreamClient, error)
	//    rpc GetWALStream (GetWALStreamRequest) returns (stream WALMessage);
	// Client-side streamingを用いてメッセージを交換する
	SendMessage(ctx context.Context, opts ...grpc.CallOption) (Replication_SendMessageClient, error)
	// Server-side streamingを用いてメッセージを交換する
	GetMessages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (Replication_GetMessagesClient, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) GetWALStream(ctx context.Context, in *GetWALStreamRequest, opts ...grpc.CallOption) (Replication_GetWALStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Replication_serviceDesc.Streams[0], "/proto.Replication/GetWALStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationGetWALStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Replication_GetWALStreamClient interface {
	Recv() (*WALMessage, error)
	grpc.ClientStream
}

type replicationGetWALStreamClient struct {
	grpc.ClientStream
}

func (x *replicationGetWALStreamClient) Recv() (*WALMessage, error) {
	m := new(WALMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicationClient) SendMessage(ctx context.Context, opts ...grpc.CallOption) (Replication_SendMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Replication_serviceDesc.Streams[1], "/proto.Replication/SendMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationSendMessageClient{stream}
	return x, nil
}

type Replication_SendMessageClient interface {
	Send(*SendRequest) error
	CloseAndRecv() (*SendResult, error)
	grpc.ClientStream
}

type replicationSendMessageClient struct {
	grpc.ClientStream
}

func (x *replicationSendMessageClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicationSendMessageClient) CloseAndRecv() (*SendResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicationClient) GetMessages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (Replication_GetMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Replication_serviceDesc.Streams[2], "/proto.Replication/GetMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationGetMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Replication_GetMessagesClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type replicationGetMessagesClient struct {
	grpc.ClientStream
}

func (x *replicationGetMessagesClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReplicationServer is the server API for Replication service.
type ReplicationServer interface {
	GetWALStream(*GetWALStreamRequest, Replication_GetWALStreamServer) error
	//    rpc GetWALStream (GetWALStreamRequest) returns (stream WALMessage);
	// Client-side streamingを用いてメッセージを交換する
	SendMessage(Replication_SendMessageServer) error
	// Server-side streamingを用いてメッセージを交換する
	GetMessages(*MessagesRequest, Replication_GetMessagesServer) error
}

// UnimplementedReplicationServer can be embedded to have forward compatible implementations.
type UnimplementedReplicationServer struct {
}

func (*UnimplementedReplicationServer) GetWALStream(req *GetWALStreamRequest, srv Replication_GetWALStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWALStream not implemented")
}
func (*UnimplementedReplicationServer) SendMessage(srv Replication_SendMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedReplicationServer) GetMessages(req *MessagesRequest, srv Replication_GetMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}

func RegisterReplicationServer(s *grpc.Server, srv ReplicationServer) {
	s.RegisterService(&_Replication_serviceDesc, srv)
}

func _Replication_GetWALStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWALStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServer).GetWALStream(m, &replicationGetWALStreamServer{stream})
}

type Replication_GetWALStreamServer interface {
	Send(*WALMessage) error
	grpc.ServerStream
}

type replicationGetWALStreamServer struct {
	grpc.ServerStream
}

func (x *replicationGetWALStreamServer) Send(m *WALMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Replication_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).SendMessage(&replicationSendMessageServer{stream})
}

type Replication_SendMessageServer interface {
	SendAndClose(*SendResult) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type replicationSendMessageServer struct {
	grpc.ServerStream
}

func (x *replicationSendMessageServer) SendAndClose(m *SendResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicationSendMessageServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Replication_GetMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationServer).GetMessages(m, &replicationGetMessagesServer{stream})
}

type Replication_GetMessagesServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type replicationGetMessagesServer struct {
	grpc.ServerStream
}

func (x *replicationGetMessagesServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

var _Replication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWALStream",
			Handler:       _Replication_GetWALStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendMessage",
			Handler:       _Replication_SendMessage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMessages",
			Handler:       _Replication_GetMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "replication.proto",
}
