root_directory: data
listen_port: 5993
log_level: info
stop_grace_period: 0
wal_rotate_interval: 5
enable_last_known: false
timezone: "America/New_York"
triggers:
  - module: ondiskagg.so
    on: "*/1Min/OHLCV"
    config:
      filter: nasdaq
      destinations: [ '5Min', '15Min', '1H', '1D' ]
bgworkers:
  - module: alpaca.so
    name: Alpaca
    config:
      ws_worker_count: 15
      minute_bar_symbols:
        - '*'
      quote_symbols:
        - VOO
        - SPY
      trade_symbols:
        - AAPL
